1 cdecl GetHSteamPipe() GetHSteamPipe_
2 cdecl GetHSteamUser() GetHSteamUser_
3 cdecl SteamAPI_GetHSteamPipe() SteamAPI_GetHSteamPipe_
4 cdecl SteamAPI_GetHSteamUser() SteamAPI_GetHSteamUser_
5 cdecl SteamAPI_GetSteamInstallPath() SteamAPI_GetSteamInstallPath_
6 cdecl SteamAPI_ISteamAppList_GetAppBuildId( long long ) SteamAPI_ISteamAppList_GetAppBuildId_
7 cdecl SteamAPI_ISteamAppList_GetAppInstallDir( long long str long ) SteamAPI_ISteamAppList_GetAppInstallDir_
8 cdecl SteamAPI_ISteamAppList_GetAppName( long long str long ) SteamAPI_ISteamAppList_GetAppName_
9 cdecl SteamAPI_ISteamAppList_GetInstalledApps( long ptr long ) SteamAPI_ISteamAppList_GetInstalledApps_
10 cdecl SteamAPI_ISteamAppList_GetNumInstalledApps( long ) SteamAPI_ISteamAppList_GetNumInstalledApps_
11 cdecl SteamAPI_ISteamApps_BGetDLCDataByIndex( long long ptr ptr str long ) SteamAPI_ISteamApps_BGetDLCDataByIndex_
12 cdecl SteamAPI_ISteamApps_BIsAppInstalled( long long ) SteamAPI_ISteamApps_BIsAppInstalled_
13 cdecl SteamAPI_ISteamApps_BIsCybercafe( long ) SteamAPI_ISteamApps_BIsCybercafe_
14 cdecl SteamAPI_ISteamApps_BIsDlcInstalled( long long ) SteamAPI_ISteamApps_BIsDlcInstalled_
15 cdecl SteamAPI_ISteamApps_BIsLowViolence( long ) SteamAPI_ISteamApps_BIsLowViolence_
16 cdecl SteamAPI_ISteamApps_BIsSubscribed( long ) SteamAPI_ISteamApps_BIsSubscribed_
17 cdecl SteamAPI_ISteamApps_BIsSubscribedApp( long long ) SteamAPI_ISteamApps_BIsSubscribedApp_
18 cdecl SteamAPI_ISteamApps_BIsSubscribedFromFreeWeekend( long ) SteamAPI_ISteamApps_BIsSubscribedFromFreeWeekend_
19 cdecl SteamAPI_ISteamApps_BIsVACBanned( long ) SteamAPI_ISteamApps_BIsVACBanned_
20 cdecl SteamAPI_ISteamApps_GetAppBuildId( long ) SteamAPI_ISteamApps_GetAppBuildId_
21 cdecl SteamAPI_ISteamApps_GetAppInstallDir( long long str long ) SteamAPI_ISteamApps_GetAppInstallDir_
22 cdecl SteamAPI_ISteamApps_GetAppOwner( long ) SteamAPI_ISteamApps_GetAppOwner_
23 cdecl SteamAPI_ISteamApps_GetAvailableGameLanguages( long ) SteamAPI_ISteamApps_GetAvailableGameLanguages_
24 cdecl SteamAPI_ISteamApps_GetCurrentBetaName( long str long ) SteamAPI_ISteamApps_GetCurrentBetaName_
25 cdecl SteamAPI_ISteamApps_GetCurrentGameLanguage( long ) SteamAPI_ISteamApps_GetCurrentGameLanguage_
26 cdecl SteamAPI_ISteamApps_GetDLCCount( long ) SteamAPI_ISteamApps_GetDLCCount_
27 cdecl SteamAPI_ISteamApps_GetDlcDownloadProgress( long long ptr ptr ) SteamAPI_ISteamApps_GetDlcDownloadProgress_
28 cdecl SteamAPI_ISteamApps_GetEarliestPurchaseUnixTime( long long ) SteamAPI_ISteamApps_GetEarliestPurchaseUnixTime_
29 cdecl SteamAPI_ISteamApps_GetInstalledDepots( long long ptr long ) SteamAPI_ISteamApps_GetInstalledDepots_
30 cdecl SteamAPI_ISteamApps_GetLaunchQueryParam( long str ) SteamAPI_ISteamApps_GetLaunchQueryParam_
31 cdecl SteamAPI_ISteamApps_InstallDLC( long long ) SteamAPI_ISteamApps_InstallDLC_
32 cdecl SteamAPI_ISteamApps_MarkContentCorrupt( long long ) SteamAPI_ISteamApps_MarkContentCorrupt_
33 cdecl SteamAPI_ISteamApps_RequestAppProofOfPurchaseKey( long long ) SteamAPI_ISteamApps_RequestAppProofOfPurchaseKey_
34 cdecl SteamAPI_ISteamApps_UninstallDLC( long long ) SteamAPI_ISteamApps_UninstallDLC_
35 cdecl SteamAPI_ISteamClient_BReleaseSteamPipe( long long ) SteamAPI_ISteamClient_BReleaseSteamPipe_
36 cdecl SteamAPI_ISteamClient_BShutdownIfAllPipesClosed( long ) SteamAPI_ISteamClient_BShutdownIfAllPipesClosed_
37 cdecl SteamAPI_ISteamClient_ConnectToGlobalUser( long long ) SteamAPI_ISteamClient_ConnectToGlobalUser_
38 cdecl SteamAPI_ISteamClient_CreateLocalUser( long ptr long ) SteamAPI_ISteamClient_CreateLocalUser_
39 cdecl SteamAPI_ISteamClient_CreateSteamPipe( long ) SteamAPI_ISteamClient_CreateSteamPipe_
40 cdecl SteamAPI_ISteamClient_GetIPCCallCount( long ) SteamAPI_ISteamClient_GetIPCCallCount_
41 cdecl SteamAPI_ISteamClient_GetISteamAppList( long long long str ) SteamAPI_ISteamClient_GetISteamAppList_
42 cdecl SteamAPI_ISteamClient_GetISteamApps( long long long str ) SteamAPI_ISteamClient_GetISteamApps_
43 cdecl SteamAPI_ISteamClient_GetISteamController( long long long str ) SteamAPI_ISteamClient_GetISteamController_
44 cdecl SteamAPI_ISteamClient_GetISteamFriends( long long long str ) SteamAPI_ISteamClient_GetISteamFriends_
45 cdecl SteamAPI_ISteamClient_GetISteamGameServer( long long long str ) SteamAPI_ISteamClient_GetISteamGameServer_
46 cdecl SteamAPI_ISteamClient_GetISteamGameServerStats( long long long str ) SteamAPI_ISteamClient_GetISteamGameServerStats_
47 cdecl SteamAPI_ISteamClient_GetISteamGenericInterface( long long long str ) SteamAPI_ISteamClient_GetISteamGenericInterface_
48 cdecl SteamAPI_ISteamClient_GetISteamHTMLSurface( long long long str ) SteamAPI_ISteamClient_GetISteamHTMLSurface_
49 cdecl SteamAPI_ISteamClient_GetISteamHTTP( long long long str ) SteamAPI_ISteamClient_GetISteamHTTP_
50 cdecl SteamAPI_ISteamClient_GetISteamInventory( long long long str ) SteamAPI_ISteamClient_GetISteamInventory_
51 cdecl SteamAPI_ISteamClient_GetISteamMatchmaking( long long long str ) SteamAPI_ISteamClient_GetISteamMatchmaking_
52 cdecl SteamAPI_ISteamClient_GetISteamMatchmakingServers( long long long str ) SteamAPI_ISteamClient_GetISteamMatchmakingServers_
53 cdecl SteamAPI_ISteamClient_GetISteamMusic( long long long str ) SteamAPI_ISteamClient_GetISteamMusic_
54 cdecl SteamAPI_ISteamClient_GetISteamMusicRemote( long long long str ) SteamAPI_ISteamClient_GetISteamMusicRemote_
55 cdecl SteamAPI_ISteamClient_GetISteamNetworking( long long long str ) SteamAPI_ISteamClient_GetISteamNetworking_
56 cdecl SteamAPI_ISteamClient_GetISteamRemoteStorage( long long long str ) SteamAPI_ISteamClient_GetISteamRemoteStorage_
57 cdecl SteamAPI_ISteamClient_GetISteamScreenshots( long long long str ) SteamAPI_ISteamClient_GetISteamScreenshots_
58 cdecl SteamAPI_ISteamClient_GetISteamUGC( long long long str ) SteamAPI_ISteamClient_GetISteamUGC_
59 cdecl SteamAPI_ISteamClient_GetISteamUnifiedMessages( long long long str ) SteamAPI_ISteamClient_GetISteamUnifiedMessages_
60 cdecl SteamAPI_ISteamClient_GetISteamUser( long long long str ) SteamAPI_ISteamClient_GetISteamUser_
61 cdecl SteamAPI_ISteamClient_GetISteamUserStats( long long long str ) SteamAPI_ISteamClient_GetISteamUserStats_
62 cdecl SteamAPI_ISteamClient_GetISteamUtils( long long str ) SteamAPI_ISteamClient_GetISteamUtils_
63 cdecl SteamAPI_ISteamClient_GetISteamVideo( long long long str ) SteamAPI_ISteamClient_GetISteamVideo_
64 cdecl SteamAPI_ISteamClient_ReleaseUser( long long long ) SteamAPI_ISteamClient_ReleaseUser_
65 stub SteamAPI_ISteamClient_Remove_SteamAPI_CPostAPIResultInProcess() 
66 stub SteamAPI_ISteamClient_RunFrame() 
67 cdecl SteamAPI_ISteamClient_SetLocalIPBinding( long long long ) SteamAPI_ISteamClient_SetLocalIPBinding_
68 cdecl SteamAPI_ISteamClient_SetWarningMessageHook( long long ) SteamAPI_ISteamClient_SetWarningMessageHook_
69 stub SteamAPI_ISteamClient_Set_SteamAPI_CCheckCallbackRegisteredInProcess() 
70 stub SteamAPI_ISteamClient_Set_SteamAPI_CPostAPIResultInProcess() 
71 stub SteamAPI_ISteamController_GetControllerState() 
72 cdecl SteamAPI_ISteamController_Init( long ) SteamAPI_ISteamController_Init_
73 cdecl SteamAPI_ISteamController_RunFrame( long ) SteamAPI_ISteamController_RunFrame_
74 stub SteamAPI_ISteamController_SetOverrideMode() 
75 cdecl SteamAPI_ISteamController_Shutdown( long ) SteamAPI_ISteamController_Shutdown_
76 cdecl SteamAPI_ISteamController_TriggerHapticPulse( long long long long ) SteamAPI_ISteamController_TriggerHapticPulse_
77 cdecl SteamAPI_ISteamFriends_ActivateGameOverlay( long str ) SteamAPI_ISteamFriends_ActivateGameOverlay_
78 cdecl SteamAPI_ISteamFriends_ActivateGameOverlayInviteDialog( long long ) SteamAPI_ISteamFriends_ActivateGameOverlayInviteDialog_
79 cdecl SteamAPI_ISteamFriends_ActivateGameOverlayToStore( long long long ) SteamAPI_ISteamFriends_ActivateGameOverlayToStore_
80 cdecl SteamAPI_ISteamFriends_ActivateGameOverlayToUser( long str long ) SteamAPI_ISteamFriends_ActivateGameOverlayToUser_
81 cdecl SteamAPI_ISteamFriends_ActivateGameOverlayToWebPage( long str ) SteamAPI_ISteamFriends_ActivateGameOverlayToWebPage_
82 cdecl SteamAPI_ISteamFriends_ClearRichPresence( long ) SteamAPI_ISteamFriends_ClearRichPresence_
83 cdecl SteamAPI_ISteamFriends_CloseClanChatWindowInSteam( long long ) SteamAPI_ISteamFriends_CloseClanChatWindowInSteam_
84 cdecl SteamAPI_ISteamFriends_DownloadClanActivityCounts( long ptr long ) SteamAPI_ISteamFriends_DownloadClanActivityCounts_
85 cdecl SteamAPI_ISteamFriends_EnumerateFollowingList( long long ) SteamAPI_ISteamFriends_EnumerateFollowingList_
86 cdecl SteamAPI_ISteamFriends_GetChatMemberByIndex( long long long ) SteamAPI_ISteamFriends_GetChatMemberByIndex_
87 cdecl SteamAPI_ISteamFriends_GetClanActivityCounts( long long ptr ptr ptr ) SteamAPI_ISteamFriends_GetClanActivityCounts_
88 cdecl SteamAPI_ISteamFriends_GetClanByIndex( long long ) SteamAPI_ISteamFriends_GetClanByIndex_
89 cdecl SteamAPI_ISteamFriends_GetClanChatMemberCount( long long ) SteamAPI_ISteamFriends_GetClanChatMemberCount_
90 cdecl SteamAPI_ISteamFriends_GetClanChatMessage( long long long ptr long ptr ptr ) SteamAPI_ISteamFriends_GetClanChatMessage_
91 cdecl SteamAPI_ISteamFriends_GetClanCount( long ) SteamAPI_ISteamFriends_GetClanCount_
92 cdecl SteamAPI_ISteamFriends_GetClanName( long long ) SteamAPI_ISteamFriends_GetClanName_
93 cdecl SteamAPI_ISteamFriends_GetClanOfficerByIndex( long long long ) SteamAPI_ISteamFriends_GetClanOfficerByIndex_
94 cdecl SteamAPI_ISteamFriends_GetClanOfficerCount( long long ) SteamAPI_ISteamFriends_GetClanOfficerCount_
95 cdecl SteamAPI_ISteamFriends_GetClanOwner( long long ) SteamAPI_ISteamFriends_GetClanOwner_
96 cdecl SteamAPI_ISteamFriends_GetClanTag( long long ) SteamAPI_ISteamFriends_GetClanTag_
97 cdecl SteamAPI_ISteamFriends_GetCoplayFriend( long long ) SteamAPI_ISteamFriends_GetCoplayFriend_
98 cdecl SteamAPI_ISteamFriends_GetCoplayFriendCount( long ) SteamAPI_ISteamFriends_GetCoplayFriendCount_
99 cdecl SteamAPI_ISteamFriends_GetFollowerCount( long long ) SteamAPI_ISteamFriends_GetFollowerCount_
100 cdecl SteamAPI_ISteamFriends_GetFriendByIndex( long long long ) SteamAPI_ISteamFriends_GetFriendByIndex_
101 cdecl SteamAPI_ISteamFriends_GetFriendCoplayGame( long long ) SteamAPI_ISteamFriends_GetFriendCoplayGame_
102 cdecl SteamAPI_ISteamFriends_GetFriendCoplayTime( long long ) SteamAPI_ISteamFriends_GetFriendCoplayTime_
103 cdecl SteamAPI_ISteamFriends_GetFriendCount( long long ) SteamAPI_ISteamFriends_GetFriendCount_
104 cdecl SteamAPI_ISteamFriends_GetFriendCountFromSource( long long ) SteamAPI_ISteamFriends_GetFriendCountFromSource_
105 cdecl SteamAPI_ISteamFriends_GetFriendFromSourceByIndex( long long long ) SteamAPI_ISteamFriends_GetFriendFromSourceByIndex_
106 cdecl SteamAPI_ISteamFriends_GetFriendGamePlayed( long long ptr ) SteamAPI_ISteamFriends_GetFriendGamePlayed_
107 cdecl SteamAPI_ISteamFriends_GetFriendMessage( long long long ptr long ptr ) SteamAPI_ISteamFriends_GetFriendMessage_
108 cdecl SteamAPI_ISteamFriends_GetFriendPersonaName( long long ) SteamAPI_ISteamFriends_GetFriendPersonaName_
109 cdecl SteamAPI_ISteamFriends_GetFriendPersonaNameHistory( long long long ) SteamAPI_ISteamFriends_GetFriendPersonaNameHistory_
110 cdecl SteamAPI_ISteamFriends_GetFriendPersonaState( long long ) SteamAPI_ISteamFriends_GetFriendPersonaState_
111 cdecl SteamAPI_ISteamFriends_GetFriendRelationship( long long ) SteamAPI_ISteamFriends_GetFriendRelationship_
112 cdecl SteamAPI_ISteamFriends_GetFriendRichPresence( long long str ) SteamAPI_ISteamFriends_GetFriendRichPresence_
113 cdecl SteamAPI_ISteamFriends_GetFriendRichPresenceKeyByIndex( long long long ) SteamAPI_ISteamFriends_GetFriendRichPresenceKeyByIndex_
114 cdecl SteamAPI_ISteamFriends_GetFriendRichPresenceKeyCount( long long ) SteamAPI_ISteamFriends_GetFriendRichPresenceKeyCount_
115 cdecl SteamAPI_ISteamFriends_GetFriendSteamLevel( long long ) SteamAPI_ISteamFriends_GetFriendSteamLevel_
116 cdecl SteamAPI_ISteamFriends_GetFriendsGroupCount( long ) SteamAPI_ISteamFriends_GetFriendsGroupCount_
117 cdecl SteamAPI_ISteamFriends_GetFriendsGroupIDByIndex( long long ) SteamAPI_ISteamFriends_GetFriendsGroupIDByIndex_
118 cdecl SteamAPI_ISteamFriends_GetFriendsGroupMembersCount( long long ) SteamAPI_ISteamFriends_GetFriendsGroupMembersCount_
119 cdecl SteamAPI_ISteamFriends_GetFriendsGroupMembersList( long long ptr long ) SteamAPI_ISteamFriends_GetFriendsGroupMembersList_
120 cdecl SteamAPI_ISteamFriends_GetFriendsGroupName( long long ) SteamAPI_ISteamFriends_GetFriendsGroupName_
121 cdecl SteamAPI_ISteamFriends_GetLargeFriendAvatar( long long ) SteamAPI_ISteamFriends_GetLargeFriendAvatar_
122 cdecl SteamAPI_ISteamFriends_GetMediumFriendAvatar( long long ) SteamAPI_ISteamFriends_GetMediumFriendAvatar_
123 cdecl SteamAPI_ISteamFriends_GetPersonaName( long ) SteamAPI_ISteamFriends_GetPersonaName_
124 cdecl SteamAPI_ISteamFriends_GetPersonaState( long ) SteamAPI_ISteamFriends_GetPersonaState_
125 cdecl SteamAPI_ISteamFriends_GetPlayerNickname( long long ) SteamAPI_ISteamFriends_GetPlayerNickname_
126 cdecl SteamAPI_ISteamFriends_GetSmallFriendAvatar( long long ) SteamAPI_ISteamFriends_GetSmallFriendAvatar_
127 cdecl SteamAPI_ISteamFriends_GetUserRestrictions( long ) SteamAPI_ISteamFriends_GetUserRestrictions_
128 cdecl SteamAPI_ISteamFriends_HasFriend( long long long ) SteamAPI_ISteamFriends_HasFriend_
129 cdecl SteamAPI_ISteamFriends_InviteUserToGame( long long str ) SteamAPI_ISteamFriends_InviteUserToGame_
130 cdecl SteamAPI_ISteamFriends_IsClanChatAdmin( long long long ) SteamAPI_ISteamFriends_IsClanChatAdmin_
131 cdecl SteamAPI_ISteamFriends_IsClanChatWindowOpenInSteam( long long ) SteamAPI_ISteamFriends_IsClanChatWindowOpenInSteam_
132 cdecl SteamAPI_ISteamFriends_IsFollowing( long long ) SteamAPI_ISteamFriends_IsFollowing_
133 cdecl SteamAPI_ISteamFriends_IsUserInSource( long long long ) SteamAPI_ISteamFriends_IsUserInSource_
134 cdecl SteamAPI_ISteamFriends_JoinClanChatRoom( long long ) SteamAPI_ISteamFriends_JoinClanChatRoom_
135 cdecl SteamAPI_ISteamFriends_LeaveClanChatRoom( long long ) SteamAPI_ISteamFriends_LeaveClanChatRoom_
136 cdecl SteamAPI_ISteamFriends_OpenClanChatWindowInSteam( long long ) SteamAPI_ISteamFriends_OpenClanChatWindowInSteam_
137 cdecl SteamAPI_ISteamFriends_ReplyToFriendMessage( long long str ) SteamAPI_ISteamFriends_ReplyToFriendMessage_
138 cdecl SteamAPI_ISteamFriends_RequestClanOfficerList( long long ) SteamAPI_ISteamFriends_RequestClanOfficerList_
139 cdecl SteamAPI_ISteamFriends_RequestFriendRichPresence( long long ) SteamAPI_ISteamFriends_RequestFriendRichPresence_
140 cdecl SteamAPI_ISteamFriends_RequestUserInformation( long long long ) SteamAPI_ISteamFriends_RequestUserInformation_
141 cdecl SteamAPI_ISteamFriends_SendClanChatMessage( long long str ) SteamAPI_ISteamFriends_SendClanChatMessage_
142 cdecl SteamAPI_ISteamFriends_SetInGameVoiceSpeaking( long long long ) SteamAPI_ISteamFriends_SetInGameVoiceSpeaking_
143 cdecl SteamAPI_ISteamFriends_SetListenForFriendsMessages( long long ) SteamAPI_ISteamFriends_SetListenForFriendsMessages_
144 cdecl SteamAPI_ISteamFriends_SetPersonaName( long str ) SteamAPI_ISteamFriends_SetPersonaName_
145 cdecl SteamAPI_ISteamFriends_SetPlayedWith( long long ) SteamAPI_ISteamFriends_SetPlayedWith_
146 cdecl SteamAPI_ISteamFriends_SetRichPresence( long str str ) SteamAPI_ISteamFriends_SetRichPresence_
147 cdecl SteamAPI_ISteamGameServerStats_ClearUserAchievement( long long str ) SteamAPI_ISteamGameServerStats_ClearUserAchievement_
148 cdecl SteamAPI_ISteamGameServerStats_GetUserAchievement( long long str ptr ) SteamAPI_ISteamGameServerStats_GetUserAchievement_
149 cdecl SteamAPI_ISteamGameServerStats_GetUserStat( long long str ptr ) SteamAPI_ISteamGameServerStats_GetUserStat_
150 cdecl SteamAPI_ISteamGameServerStats_GetUserStat0( long long str ptr ) SteamAPI_ISteamGameServerStats_GetUserStat0_
151 cdecl SteamAPI_ISteamGameServerStats_RequestUserStats( long long ) SteamAPI_ISteamGameServerStats_RequestUserStats_
152 cdecl SteamAPI_ISteamGameServerStats_SetUserAchievement( long long str ) SteamAPI_ISteamGameServerStats_SetUserAchievement_
153 cdecl SteamAPI_ISteamGameServerStats_SetUserStat( long long str long ) SteamAPI_ISteamGameServerStats_SetUserStat_
154 cdecl SteamAPI_ISteamGameServerStats_SetUserStat0( long long str long ) SteamAPI_ISteamGameServerStats_SetUserStat0_
155 cdecl SteamAPI_ISteamGameServerStats_StoreUserStats( long long ) SteamAPI_ISteamGameServerStats_StoreUserStats_
156 cdecl SteamAPI_ISteamGameServerStats_UpdateUserAvgRateStat( long long str long long ) SteamAPI_ISteamGameServerStats_UpdateUserAvgRateStat_
157 cdecl SteamAPI_ISteamGameServer_AssociateWithClan( long long ) SteamAPI_ISteamGameServer_AssociateWithClan_
158 cdecl SteamAPI_ISteamGameServer_BLoggedOn( long ) SteamAPI_ISteamGameServer_BLoggedOn_
159 cdecl SteamAPI_ISteamGameServer_BSecure( long ) SteamAPI_ISteamGameServer_BSecure_
160 cdecl SteamAPI_ISteamGameServer_BUpdateUserData( long long str long ) SteamAPI_ISteamGameServer_BUpdateUserData_
161 cdecl SteamAPI_ISteamGameServer_BeginAuthSession( long ptr long long ) SteamAPI_ISteamGameServer_BeginAuthSession_
162 cdecl SteamAPI_ISteamGameServer_CancelAuthTicket( long long ) SteamAPI_ISteamGameServer_CancelAuthTicket_
163 cdecl SteamAPI_ISteamGameServer_ClearAllKeyValues( long ) SteamAPI_ISteamGameServer_ClearAllKeyValues_
164 cdecl SteamAPI_ISteamGameServer_ComputeNewPlayerCompatibility( long long ) SteamAPI_ISteamGameServer_ComputeNewPlayerCompatibility_
165 cdecl SteamAPI_ISteamGameServer_CreateUnauthenticatedUserConnection( long ) SteamAPI_ISteamGameServer_CreateUnauthenticatedUserConnection_
166 cdecl SteamAPI_ISteamGameServer_EnableHeartbeats( long long ) SteamAPI_ISteamGameServer_EnableHeartbeats_
167 cdecl SteamAPI_ISteamGameServer_EndAuthSession( long long ) SteamAPI_ISteamGameServer_EndAuthSession_
168 cdecl SteamAPI_ISteamGameServer_ForceHeartbeat( long ) SteamAPI_ISteamGameServer_ForceHeartbeat_
169 cdecl SteamAPI_ISteamGameServer_GetAuthSessionTicket( long ptr long ptr ) SteamAPI_ISteamGameServer_GetAuthSessionTicket_
170 cdecl SteamAPI_ISteamGameServer_GetGameplayStats( long ) SteamAPI_ISteamGameServer_GetGameplayStats_
171 cdecl SteamAPI_ISteamGameServer_GetNextOutgoingPacket( long ptr long ptr ptr ) SteamAPI_ISteamGameServer_GetNextOutgoingPacket_
172 cdecl SteamAPI_ISteamGameServer_GetPublicIP( long ) SteamAPI_ISteamGameServer_GetPublicIP_
173 cdecl SteamAPI_ISteamGameServer_GetServerReputation( long ) SteamAPI_ISteamGameServer_GetServerReputation_
174 cdecl SteamAPI_ISteamGameServer_GetSteamID( long ) SteamAPI_ISteamGameServer_GetSteamID_
175 cdecl SteamAPI_ISteamGameServer_HandleIncomingPacket( long ptr long long long ) SteamAPI_ISteamGameServer_HandleIncomingPacket_
176 cdecl SteamAPI_ISteamGameServer_InitGameServer( long long long long long long str ) SteamAPI_ISteamGameServer_InitGameServer_
177 cdecl SteamAPI_ISteamGameServer_LogOff( long ) SteamAPI_ISteamGameServer_LogOff_
178 cdecl SteamAPI_ISteamGameServer_LogOn( long str ) SteamAPI_ISteamGameServer_LogOn_
179 cdecl SteamAPI_ISteamGameServer_LogOnAnonymous( long ) SteamAPI_ISteamGameServer_LogOnAnonymous_
180 cdecl SteamAPI_ISteamGameServer_RequestUserGroupStatus( long long long ) SteamAPI_ISteamGameServer_RequestUserGroupStatus_
181 cdecl SteamAPI_ISteamGameServer_SendUserConnectAndAuthenticate( long long ptr long ptr ) SteamAPI_ISteamGameServer_SendUserConnectAndAuthenticate_
182 cdecl SteamAPI_ISteamGameServer_SendUserDisconnect( long long ) SteamAPI_ISteamGameServer_SendUserDisconnect_
183 cdecl SteamAPI_ISteamGameServer_SetBotPlayerCount( long long ) SteamAPI_ISteamGameServer_SetBotPlayerCount_
184 cdecl SteamAPI_ISteamGameServer_SetDedicatedServer( long long ) SteamAPI_ISteamGameServer_SetDedicatedServer_
185 cdecl SteamAPI_ISteamGameServer_SetGameData( long str ) SteamAPI_ISteamGameServer_SetGameData_
186 cdecl SteamAPI_ISteamGameServer_SetGameDescription( long str ) SteamAPI_ISteamGameServer_SetGameDescription_
187 cdecl SteamAPI_ISteamGameServer_SetGameTags( long str ) SteamAPI_ISteamGameServer_SetGameTags_
188 cdecl SteamAPI_ISteamGameServer_SetHeartbeatInterval( long long ) SteamAPI_ISteamGameServer_SetHeartbeatInterval_
189 cdecl SteamAPI_ISteamGameServer_SetKeyValue( long str str ) SteamAPI_ISteamGameServer_SetKeyValue_
190 cdecl SteamAPI_ISteamGameServer_SetMapName( long str ) SteamAPI_ISteamGameServer_SetMapName_
191 cdecl SteamAPI_ISteamGameServer_SetMaxPlayerCount( long long ) SteamAPI_ISteamGameServer_SetMaxPlayerCount_
192 cdecl SteamAPI_ISteamGameServer_SetModDir( long str ) SteamAPI_ISteamGameServer_SetModDir_
193 cdecl SteamAPI_ISteamGameServer_SetPasswordProtected( long long ) SteamAPI_ISteamGameServer_SetPasswordProtected_
194 cdecl SteamAPI_ISteamGameServer_SetProduct( long str ) SteamAPI_ISteamGameServer_SetProduct_
195 cdecl SteamAPI_ISteamGameServer_SetRegion( long str ) SteamAPI_ISteamGameServer_SetRegion_
196 cdecl SteamAPI_ISteamGameServer_SetServerName( long str ) SteamAPI_ISteamGameServer_SetServerName_
197 cdecl SteamAPI_ISteamGameServer_SetSpectatorPort( long long ) SteamAPI_ISteamGameServer_SetSpectatorPort_
198 cdecl SteamAPI_ISteamGameServer_SetSpectatorServerName( long str ) SteamAPI_ISteamGameServer_SetSpectatorServerName_
199 cdecl SteamAPI_ISteamGameServer_UserHasLicenseForApp( long long long ) SteamAPI_ISteamGameServer_UserHasLicenseForApp_
200 cdecl SteamAPI_ISteamGameServer_WasRestartRequested( long ) SteamAPI_ISteamGameServer_WasRestartRequested_
201 cdecl SteamAPI_ISteamHTMLSurface_AddHeader( long long str str ) SteamAPI_ISteamHTMLSurface_AddHeader_
202 cdecl SteamAPI_ISteamHTMLSurface_AllowStartRequest( long long long ) SteamAPI_ISteamHTMLSurface_AllowStartRequest_
203 cdecl SteamAPI_ISteamHTMLSurface_CopyToClipboard( long long ) SteamAPI_ISteamHTMLSurface_CopyToClipboard_
204 cdecl SteamAPI_ISteamHTMLSurface_CreateBrowser( long str str ) SteamAPI_ISteamHTMLSurface_CreateBrowser_
205 cdecl SteamAPI_ISteamHTMLSurface_DestructISteamHTMLSurface( long ) SteamAPI_ISteamHTMLSurface_DestructISteamHTMLSurface_
206 cdecl SteamAPI_ISteamHTMLSurface_ExecuteJavascript( long long str ) SteamAPI_ISteamHTMLSurface_ExecuteJavascript_
207 stub SteamAPI_ISteamHTMLSurface_FileLoadDialogResponse() 
208 cdecl SteamAPI_ISteamHTMLSurface_Find( long long str long long ) SteamAPI_ISteamHTMLSurface_Find_
209 cdecl SteamAPI_ISteamHTMLSurface_GetLinkAtPosition( long long long long ) SteamAPI_ISteamHTMLSurface_GetLinkAtPosition_
210 cdecl SteamAPI_ISteamHTMLSurface_GoBack( long long ) SteamAPI_ISteamHTMLSurface_GoBack_
211 cdecl SteamAPI_ISteamHTMLSurface_GoForward( long long ) SteamAPI_ISteamHTMLSurface_GoForward_
212 cdecl SteamAPI_ISteamHTMLSurface_Init( long ) SteamAPI_ISteamHTMLSurface_Init_
213 cdecl SteamAPI_ISteamHTMLSurface_JSDialogResponse( long long long ) SteamAPI_ISteamHTMLSurface_JSDialogResponse_
214 cdecl SteamAPI_ISteamHTMLSurface_KeyChar( long long long long ) SteamAPI_ISteamHTMLSurface_KeyChar_
215 cdecl SteamAPI_ISteamHTMLSurface_KeyDown( long long long long ) SteamAPI_ISteamHTMLSurface_KeyDown_
216 cdecl SteamAPI_ISteamHTMLSurface_KeyUp( long long long long ) SteamAPI_ISteamHTMLSurface_KeyUp_
217 cdecl SteamAPI_ISteamHTMLSurface_LoadURL( long long str str ) SteamAPI_ISteamHTMLSurface_LoadURL_
218 cdecl SteamAPI_ISteamHTMLSurface_MouseDoubleClick( long long long ) SteamAPI_ISteamHTMLSurface_MouseDoubleClick_
219 cdecl SteamAPI_ISteamHTMLSurface_MouseDown( long long long ) SteamAPI_ISteamHTMLSurface_MouseDown_
220 cdecl SteamAPI_ISteamHTMLSurface_MouseMove( long long long long ) SteamAPI_ISteamHTMLSurface_MouseMove_
221 cdecl SteamAPI_ISteamHTMLSurface_MouseUp( long long long ) SteamAPI_ISteamHTMLSurface_MouseUp_
222 cdecl SteamAPI_ISteamHTMLSurface_MouseWheel( long long long ) SteamAPI_ISteamHTMLSurface_MouseWheel_
223 cdecl SteamAPI_ISteamHTMLSurface_PasteFromClipboard( long long ) SteamAPI_ISteamHTMLSurface_PasteFromClipboard_
224 cdecl SteamAPI_ISteamHTMLSurface_Reload( long long ) SteamAPI_ISteamHTMLSurface_Reload_
225 cdecl SteamAPI_ISteamHTMLSurface_RemoveBrowser( long long ) SteamAPI_ISteamHTMLSurface_RemoveBrowser_
226 cdecl SteamAPI_ISteamHTMLSurface_SetBackgroundMode( long long long ) SteamAPI_ISteamHTMLSurface_SetBackgroundMode_
227 cdecl SteamAPI_ISteamHTMLSurface_SetCookie( long str str str str long long long ) SteamAPI_ISteamHTMLSurface_SetCookie_
228 cdecl SteamAPI_ISteamHTMLSurface_SetHorizontalScroll( long long long ) SteamAPI_ISteamHTMLSurface_SetHorizontalScroll_
229 cdecl SteamAPI_ISteamHTMLSurface_SetKeyFocus( long long long ) SteamAPI_ISteamHTMLSurface_SetKeyFocus_
230 cdecl SteamAPI_ISteamHTMLSurface_SetPageScaleFactor( long long long long long ) SteamAPI_ISteamHTMLSurface_SetPageScaleFactor_
231 cdecl SteamAPI_ISteamHTMLSurface_SetSize( long long long long ) SteamAPI_ISteamHTMLSurface_SetSize_
232 cdecl SteamAPI_ISteamHTMLSurface_SetVerticalScroll( long long long ) SteamAPI_ISteamHTMLSurface_SetVerticalScroll_
233 cdecl SteamAPI_ISteamHTMLSurface_Shutdown( long ) SteamAPI_ISteamHTMLSurface_Shutdown_
234 cdecl SteamAPI_ISteamHTMLSurface_StopFind( long long ) SteamAPI_ISteamHTMLSurface_StopFind_
235 cdecl SteamAPI_ISteamHTMLSurface_StopLoad( long long ) SteamAPI_ISteamHTMLSurface_StopLoad_
236 cdecl SteamAPI_ISteamHTMLSurface_ViewSource( long long ) SteamAPI_ISteamHTMLSurface_ViewSource_
237 cdecl SteamAPI_ISteamHTTP_CreateCookieContainer( long long ) SteamAPI_ISteamHTTP_CreateCookieContainer_
238 cdecl SteamAPI_ISteamHTTP_CreateHTTPRequest( long long str ) SteamAPI_ISteamHTTP_CreateHTTPRequest_
239 cdecl SteamAPI_ISteamHTTP_DeferHTTPRequest( long long ) SteamAPI_ISteamHTTP_DeferHTTPRequest_
240 cdecl SteamAPI_ISteamHTTP_GetHTTPDownloadProgressPct( long long ptr ) SteamAPI_ISteamHTTP_GetHTTPDownloadProgressPct_
241 cdecl SteamAPI_ISteamHTTP_GetHTTPRequestWasTimedOut( long long ptr ) SteamAPI_ISteamHTTP_GetHTTPRequestWasTimedOut_
242 cdecl SteamAPI_ISteamHTTP_GetHTTPResponseBodyData( long long ptr long ) SteamAPI_ISteamHTTP_GetHTTPResponseBodyData_
243 cdecl SteamAPI_ISteamHTTP_GetHTTPResponseBodySize( long long ptr ) SteamAPI_ISteamHTTP_GetHTTPResponseBodySize_
244 cdecl SteamAPI_ISteamHTTP_GetHTTPResponseHeaderSize( long long str ptr ) SteamAPI_ISteamHTTP_GetHTTPResponseHeaderSize_
245 cdecl SteamAPI_ISteamHTTP_GetHTTPResponseHeaderValue( long long str ptr long ) SteamAPI_ISteamHTTP_GetHTTPResponseHeaderValue_
246 cdecl SteamAPI_ISteamHTTP_GetHTTPStreamingResponseBodyData( long long long ptr long ) SteamAPI_ISteamHTTP_GetHTTPStreamingResponseBodyData_
247 cdecl SteamAPI_ISteamHTTP_PrioritizeHTTPRequest( long long ) SteamAPI_ISteamHTTP_PrioritizeHTTPRequest_
248 cdecl SteamAPI_ISteamHTTP_ReleaseCookieContainer( long long ) SteamAPI_ISteamHTTP_ReleaseCookieContainer_
249 cdecl SteamAPI_ISteamHTTP_ReleaseHTTPRequest( long long ) SteamAPI_ISteamHTTP_ReleaseHTTPRequest_
250 cdecl SteamAPI_ISteamHTTP_SendHTTPRequest( long long ptr ) SteamAPI_ISteamHTTP_SendHTTPRequest_
251 cdecl SteamAPI_ISteamHTTP_SendHTTPRequestAndStreamResponse( long long ptr ) SteamAPI_ISteamHTTP_SendHTTPRequestAndStreamResponse_
252 cdecl SteamAPI_ISteamHTTP_SetCookie( long long str str str ) SteamAPI_ISteamHTTP_SetCookie_
253 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestAbsoluteTimeoutMS( long long long ) SteamAPI_ISteamHTTP_SetHTTPRequestAbsoluteTimeoutMS_
254 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestContextValue( long long long ) SteamAPI_ISteamHTTP_SetHTTPRequestContextValue_
255 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestCookieContainer( long long long ) SteamAPI_ISteamHTTP_SetHTTPRequestCookieContainer_
256 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestGetOrPostParameter( long long str str ) SteamAPI_ISteamHTTP_SetHTTPRequestGetOrPostParameter_
257 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestHeaderValue( long long str str ) SteamAPI_ISteamHTTP_SetHTTPRequestHeaderValue_
258 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestNetworkActivityTimeout( long long long ) SteamAPI_ISteamHTTP_SetHTTPRequestNetworkActivityTimeout_
259 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestRawPostBody( long long str ptr long ) SteamAPI_ISteamHTTP_SetHTTPRequestRawPostBody_
260 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestRequiresVerifiedCertificate( long long long ) SteamAPI_ISteamHTTP_SetHTTPRequestRequiresVerifiedCertificate_
261 cdecl SteamAPI_ISteamHTTP_SetHTTPRequestUserAgentInfo( long long str ) SteamAPI_ISteamHTTP_SetHTTPRequestUserAgentInfo_
262 cdecl SteamAPI_ISteamInventory_AddPromoItem( long ptr long ) SteamAPI_ISteamInventory_AddPromoItem_
263 cdecl SteamAPI_ISteamInventory_AddPromoItems( long ptr ptr long ) SteamAPI_ISteamInventory_AddPromoItems_
264 cdecl SteamAPI_ISteamInventory_CheckResultSteamID( long long long ) SteamAPI_ISteamInventory_CheckResultSteamID_
265 cdecl SteamAPI_ISteamInventory_ConsumeItem( long ptr long long ) SteamAPI_ISteamInventory_ConsumeItem_
266 cdecl SteamAPI_ISteamInventory_DeserializeResult( long ptr ptr long long ) SteamAPI_ISteamInventory_DeserializeResult_
267 cdecl SteamAPI_ISteamInventory_DestroyResult( long long ) SteamAPI_ISteamInventory_DestroyResult_
268 cdecl SteamAPI_ISteamInventory_ExchangeItems( long ptr ptr ptr long ptr ptr long ) SteamAPI_ISteamInventory_ExchangeItems_
269 cdecl SteamAPI_ISteamInventory_GenerateItems( long ptr ptr ptr long ) SteamAPI_ISteamInventory_GenerateItems_
270 cdecl SteamAPI_ISteamInventory_GetAllItems( long ptr ) SteamAPI_ISteamInventory_GetAllItems_
271 cdecl SteamAPI_ISteamInventory_GetItemDefinitionIDs( long ptr ptr ) SteamAPI_ISteamInventory_GetItemDefinitionIDs_
272 cdecl SteamAPI_ISteamInventory_GetItemDefinitionProperty( long long str str ptr ) SteamAPI_ISteamInventory_GetItemDefinitionProperty_
273 cdecl SteamAPI_ISteamInventory_GetItemsByID( long ptr ptr long ) SteamAPI_ISteamInventory_GetItemsByID_
274 cdecl SteamAPI_ISteamInventory_GetResultItems( long long ptr ptr ) SteamAPI_ISteamInventory_GetResultItems_
275 cdecl SteamAPI_ISteamInventory_GetResultStatus( long long ) SteamAPI_ISteamInventory_GetResultStatus_
276 cdecl SteamAPI_ISteamInventory_GetResultTimestamp( long long ) SteamAPI_ISteamInventory_GetResultTimestamp_
277 cdecl SteamAPI_ISteamInventory_GrantPromoItems( long ptr ) SteamAPI_ISteamInventory_GrantPromoItems_
278 cdecl SteamAPI_ISteamInventory_LoadItemDefinitions( long ) SteamAPI_ISteamInventory_LoadItemDefinitions_
279 cdecl SteamAPI_ISteamInventory_SendItemDropHeartbeat( long ) SteamAPI_ISteamInventory_SendItemDropHeartbeat_
280 cdecl SteamAPI_ISteamInventory_SerializeResult( long long ptr ptr ) SteamAPI_ISteamInventory_SerializeResult_
281 cdecl SteamAPI_ISteamInventory_TradeItems( long ptr long ptr ptr long ptr ptr long ) SteamAPI_ISteamInventory_TradeItems_
282 cdecl SteamAPI_ISteamInventory_TransferItemQuantity( long ptr long long long ) SteamAPI_ISteamInventory_TransferItemQuantity_
283 cdecl SteamAPI_ISteamInventory_TriggerItemDrop( long ptr long ) SteamAPI_ISteamInventory_TriggerItemDrop_
284 cdecl SteamAPI_ISteamMatchmakingPingResponse_ServerFailedToRespond( long ) SteamAPI_ISteamMatchmakingPingResponse_ServerFailedToRespond_
285 cdecl SteamAPI_ISteamMatchmakingPingResponse_ServerResponded( long long ) SteamAPI_ISteamMatchmakingPingResponse_ServerResponded_
286 cdecl SteamAPI_ISteamMatchmakingPlayersResponse_AddPlayerToList( long str long long ) SteamAPI_ISteamMatchmakingPlayersResponse_AddPlayerToList_
287 cdecl SteamAPI_ISteamMatchmakingPlayersResponse_PlayersFailedToRespond( long ) SteamAPI_ISteamMatchmakingPlayersResponse_PlayersFailedToRespond_
288 cdecl SteamAPI_ISteamMatchmakingPlayersResponse_PlayersRefreshComplete( long ) SteamAPI_ISteamMatchmakingPlayersResponse_PlayersRefreshComplete_
289 cdecl SteamAPI_ISteamMatchmakingRulesResponse_RulesFailedToRespond( long ) SteamAPI_ISteamMatchmakingRulesResponse_RulesFailedToRespond_
290 cdecl SteamAPI_ISteamMatchmakingRulesResponse_RulesRefreshComplete( long ) SteamAPI_ISteamMatchmakingRulesResponse_RulesRefreshComplete_
291 cdecl SteamAPI_ISteamMatchmakingRulesResponse_RulesResponded( long str str ) SteamAPI_ISteamMatchmakingRulesResponse_RulesResponded_
292 cdecl SteamAPI_ISteamMatchmakingServerListResponse_RefreshComplete( long long long ) SteamAPI_ISteamMatchmakingServerListResponse_RefreshComplete_
293 cdecl SteamAPI_ISteamMatchmakingServerListResponse_ServerFailedToRespond( long long long ) SteamAPI_ISteamMatchmakingServerListResponse_ServerFailedToRespond_
294 cdecl SteamAPI_ISteamMatchmakingServerListResponse_ServerResponded( long long long ) SteamAPI_ISteamMatchmakingServerListResponse_ServerResponded_
295 cdecl SteamAPI_ISteamMatchmakingServers_CancelQuery( long long ) SteamAPI_ISteamMatchmakingServers_CancelQuery_
296 cdecl SteamAPI_ISteamMatchmakingServers_CancelServerQuery( long long ) SteamAPI_ISteamMatchmakingServers_CancelServerQuery_
297 cdecl SteamAPI_ISteamMatchmakingServers_GetServerCount( long long ) SteamAPI_ISteamMatchmakingServers_GetServerCount_
298 cdecl SteamAPI_ISteamMatchmakingServers_GetServerDetails( long long long ) SteamAPI_ISteamMatchmakingServers_GetServerDetails_
299 cdecl SteamAPI_ISteamMatchmakingServers_IsRefreshing( long long ) SteamAPI_ISteamMatchmakingServers_IsRefreshing_
300 cdecl SteamAPI_ISteamMatchmakingServers_PingServer( long long long ptr ) SteamAPI_ISteamMatchmakingServers_PingServer_
301 cdecl SteamAPI_ISteamMatchmakingServers_PlayerDetails( long long long ptr ) SteamAPI_ISteamMatchmakingServers_PlayerDetails_
302 cdecl SteamAPI_ISteamMatchmakingServers_RefreshQuery( long long ) SteamAPI_ISteamMatchmakingServers_RefreshQuery_
303 cdecl SteamAPI_ISteamMatchmakingServers_RefreshServer( long long long ) SteamAPI_ISteamMatchmakingServers_RefreshServer_
304 cdecl SteamAPI_ISteamMatchmakingServers_ReleaseRequest( long long ) SteamAPI_ISteamMatchmakingServers_ReleaseRequest_
305 cdecl SteamAPI_ISteamMatchmakingServers_RequestFavoritesServerList( long long ptr long ptr ) SteamAPI_ISteamMatchmakingServers_RequestFavoritesServerList_
306 cdecl SteamAPI_ISteamMatchmakingServers_RequestFriendsServerList( long long ptr long ptr ) SteamAPI_ISteamMatchmakingServers_RequestFriendsServerList_
307 cdecl SteamAPI_ISteamMatchmakingServers_RequestHistoryServerList( long long ptr long ptr ) SteamAPI_ISteamMatchmakingServers_RequestHistoryServerList_
308 cdecl SteamAPI_ISteamMatchmakingServers_RequestInternetServerList( long long ptr long ptr ) SteamAPI_ISteamMatchmakingServers_RequestInternetServerList_
309 cdecl SteamAPI_ISteamMatchmakingServers_RequestLANServerList( long long ptr ) SteamAPI_ISteamMatchmakingServers_RequestLANServerList_
310 cdecl SteamAPI_ISteamMatchmakingServers_RequestSpectatorServerList( long long ptr long ptr ) SteamAPI_ISteamMatchmakingServers_RequestSpectatorServerList_
311 cdecl SteamAPI_ISteamMatchmakingServers_ServerRules( long long long ptr ) SteamAPI_ISteamMatchmakingServers_ServerRules_
312 cdecl SteamAPI_ISteamMatchmaking_AddFavoriteGame( long long long long long long long ) SteamAPI_ISteamMatchmaking_AddFavoriteGame_
313 cdecl SteamAPI_ISteamMatchmaking_AddRequestLobbyListCompatibleMembersFilter( long long ) SteamAPI_ISteamMatchmaking_AddRequestLobbyListCompatibleMembersFilter_
314 cdecl SteamAPI_ISteamMatchmaking_AddRequestLobbyListDistanceFilter( long long ) SteamAPI_ISteamMatchmaking_AddRequestLobbyListDistanceFilter_
315 cdecl SteamAPI_ISteamMatchmaking_AddRequestLobbyListFilterSlotsAvailable( long long ) SteamAPI_ISteamMatchmaking_AddRequestLobbyListFilterSlotsAvailable_
316 cdecl SteamAPI_ISteamMatchmaking_AddRequestLobbyListNearValueFilter( long str long ) SteamAPI_ISteamMatchmaking_AddRequestLobbyListNearValueFilter_
317 cdecl SteamAPI_ISteamMatchmaking_AddRequestLobbyListNumericalFilter( long str long long ) SteamAPI_ISteamMatchmaking_AddRequestLobbyListNumericalFilter_
318 cdecl SteamAPI_ISteamMatchmaking_AddRequestLobbyListResultCountFilter( long long ) SteamAPI_ISteamMatchmaking_AddRequestLobbyListResultCountFilter_
319 cdecl SteamAPI_ISteamMatchmaking_AddRequestLobbyListStringFilter( long str str long ) SteamAPI_ISteamMatchmaking_AddRequestLobbyListStringFilter_
320 cdecl SteamAPI_ISteamMatchmaking_CreateLobby( long long long ) SteamAPI_ISteamMatchmaking_CreateLobby_
321 cdecl SteamAPI_ISteamMatchmaking_DeleteLobbyData( long long str ) SteamAPI_ISteamMatchmaking_DeleteLobbyData_
322 cdecl SteamAPI_ISteamMatchmaking_GetFavoriteGame( long long ptr ptr ptr ptr ptr ptr ) SteamAPI_ISteamMatchmaking_GetFavoriteGame_
323 cdecl SteamAPI_ISteamMatchmaking_GetFavoriteGameCount( long ) SteamAPI_ISteamMatchmaking_GetFavoriteGameCount_
324 cdecl SteamAPI_ISteamMatchmaking_GetLobbyByIndex( long long ) SteamAPI_ISteamMatchmaking_GetLobbyByIndex_
325 cdecl SteamAPI_ISteamMatchmaking_GetLobbyChatEntry( long long long ptr ptr long ptr ) SteamAPI_ISteamMatchmaking_GetLobbyChatEntry_
326 cdecl SteamAPI_ISteamMatchmaking_GetLobbyData( long long str ) SteamAPI_ISteamMatchmaking_GetLobbyData_
327 cdecl SteamAPI_ISteamMatchmaking_GetLobbyDataByIndex( long long long str long str long ) SteamAPI_ISteamMatchmaking_GetLobbyDataByIndex_
328 cdecl SteamAPI_ISteamMatchmaking_GetLobbyDataCount( long long ) SteamAPI_ISteamMatchmaking_GetLobbyDataCount_
329 cdecl SteamAPI_ISteamMatchmaking_GetLobbyGameServer( long long ptr ptr ptr ) SteamAPI_ISteamMatchmaking_GetLobbyGameServer_
330 cdecl SteamAPI_ISteamMatchmaking_GetLobbyMemberByIndex( long long long ) SteamAPI_ISteamMatchmaking_GetLobbyMemberByIndex_
331 cdecl SteamAPI_ISteamMatchmaking_GetLobbyMemberData( long long long str ) SteamAPI_ISteamMatchmaking_GetLobbyMemberData_
332 cdecl SteamAPI_ISteamMatchmaking_GetLobbyMemberLimit( long long ) SteamAPI_ISteamMatchmaking_GetLobbyMemberLimit_
333 cdecl SteamAPI_ISteamMatchmaking_GetLobbyOwner( long long ) SteamAPI_ISteamMatchmaking_GetLobbyOwner_
334 cdecl SteamAPI_ISteamMatchmaking_GetNumLobbyMembers( long long ) SteamAPI_ISteamMatchmaking_GetNumLobbyMembers_
335 cdecl SteamAPI_ISteamMatchmaking_InviteUserToLobby( long long long ) SteamAPI_ISteamMatchmaking_InviteUserToLobby_
336 cdecl SteamAPI_ISteamMatchmaking_JoinLobby( long long ) SteamAPI_ISteamMatchmaking_JoinLobby_
337 cdecl SteamAPI_ISteamMatchmaking_LeaveLobby( long long ) SteamAPI_ISteamMatchmaking_LeaveLobby_
338 cdecl SteamAPI_ISteamMatchmaking_RemoveFavoriteGame( long long long long long long ) SteamAPI_ISteamMatchmaking_RemoveFavoriteGame_
339 cdecl SteamAPI_ISteamMatchmaking_RequestLobbyData( long long ) SteamAPI_ISteamMatchmaking_RequestLobbyData_
340 cdecl SteamAPI_ISteamMatchmaking_RequestLobbyList( long ) SteamAPI_ISteamMatchmaking_RequestLobbyList_
341 cdecl SteamAPI_ISteamMatchmaking_SendLobbyChatMsg( long long ptr long ) SteamAPI_ISteamMatchmaking_SendLobbyChatMsg_
342 cdecl SteamAPI_ISteamMatchmaking_SetLinkedLobby( long long long ) SteamAPI_ISteamMatchmaking_SetLinkedLobby_
343 cdecl SteamAPI_ISteamMatchmaking_SetLobbyData( long long str str ) SteamAPI_ISteamMatchmaking_SetLobbyData_
344 cdecl SteamAPI_ISteamMatchmaking_SetLobbyGameServer( long long long long long ) SteamAPI_ISteamMatchmaking_SetLobbyGameServer_
345 cdecl SteamAPI_ISteamMatchmaking_SetLobbyJoinable( long long long ) SteamAPI_ISteamMatchmaking_SetLobbyJoinable_
346 cdecl SteamAPI_ISteamMatchmaking_SetLobbyMemberData( long long str str ) SteamAPI_ISteamMatchmaking_SetLobbyMemberData_
347 cdecl SteamAPI_ISteamMatchmaking_SetLobbyMemberLimit( long long long ) SteamAPI_ISteamMatchmaking_SetLobbyMemberLimit_
348 cdecl SteamAPI_ISteamMatchmaking_SetLobbyOwner( long long long ) SteamAPI_ISteamMatchmaking_SetLobbyOwner_
349 cdecl SteamAPI_ISteamMatchmaking_SetLobbyType( long long long ) SteamAPI_ISteamMatchmaking_SetLobbyType_
350 cdecl SteamAPI_ISteamMusicRemote_BActivationSuccess( long long ) SteamAPI_ISteamMusicRemote_BActivationSuccess_
351 cdecl SteamAPI_ISteamMusicRemote_BIsCurrentMusicRemote( long ) SteamAPI_ISteamMusicRemote_BIsCurrentMusicRemote_
352 cdecl SteamAPI_ISteamMusicRemote_CurrentEntryDidChange( long ) SteamAPI_ISteamMusicRemote_CurrentEntryDidChange_
353 cdecl SteamAPI_ISteamMusicRemote_CurrentEntryIsAvailable( long long ) SteamAPI_ISteamMusicRemote_CurrentEntryIsAvailable_
354 cdecl SteamAPI_ISteamMusicRemote_CurrentEntryWillChange( long ) SteamAPI_ISteamMusicRemote_CurrentEntryWillChange_
355 cdecl SteamAPI_ISteamMusicRemote_DeregisterSteamMusicRemote( long ) SteamAPI_ISteamMusicRemote_DeregisterSteamMusicRemote_
356 cdecl SteamAPI_ISteamMusicRemote_EnableLooped( long long ) SteamAPI_ISteamMusicRemote_EnableLooped_
357 cdecl SteamAPI_ISteamMusicRemote_EnablePlayNext( long long ) SteamAPI_ISteamMusicRemote_EnablePlayNext_
358 cdecl SteamAPI_ISteamMusicRemote_EnablePlayPrevious( long long ) SteamAPI_ISteamMusicRemote_EnablePlayPrevious_
359 cdecl SteamAPI_ISteamMusicRemote_EnablePlaylists( long long ) SteamAPI_ISteamMusicRemote_EnablePlaylists_
360 cdecl SteamAPI_ISteamMusicRemote_EnableQueue( long long ) SteamAPI_ISteamMusicRemote_EnableQueue_
361 cdecl SteamAPI_ISteamMusicRemote_EnableShuffled( long long ) SteamAPI_ISteamMusicRemote_EnableShuffled_
362 cdecl SteamAPI_ISteamMusicRemote_PlaylistDidChange( long ) SteamAPI_ISteamMusicRemote_PlaylistDidChange_
363 cdecl SteamAPI_ISteamMusicRemote_PlaylistWillChange( long ) SteamAPI_ISteamMusicRemote_PlaylistWillChange_
364 cdecl SteamAPI_ISteamMusicRemote_QueueDidChange( long ) SteamAPI_ISteamMusicRemote_QueueDidChange_
365 cdecl SteamAPI_ISteamMusicRemote_QueueWillChange( long ) SteamAPI_ISteamMusicRemote_QueueWillChange_
366 cdecl SteamAPI_ISteamMusicRemote_RegisterSteamMusicRemote( long str ) SteamAPI_ISteamMusicRemote_RegisterSteamMusicRemote_
367 cdecl SteamAPI_ISteamMusicRemote_ResetPlaylistEntries( long ) SteamAPI_ISteamMusicRemote_ResetPlaylistEntries_
368 cdecl SteamAPI_ISteamMusicRemote_ResetQueueEntries( long ) SteamAPI_ISteamMusicRemote_ResetQueueEntries_
369 cdecl SteamAPI_ISteamMusicRemote_SetCurrentPlaylistEntry( long long ) SteamAPI_ISteamMusicRemote_SetCurrentPlaylistEntry_
370 cdecl SteamAPI_ISteamMusicRemote_SetCurrentQueueEntry( long long ) SteamAPI_ISteamMusicRemote_SetCurrentQueueEntry_
371 cdecl SteamAPI_ISteamMusicRemote_SetDisplayName( long str ) SteamAPI_ISteamMusicRemote_SetDisplayName_
372 cdecl SteamAPI_ISteamMusicRemote_SetPNGIcon_64x64( long ptr long ) SteamAPI_ISteamMusicRemote_SetPNGIcon_64x64_
373 cdecl SteamAPI_ISteamMusicRemote_SetPlaylistEntry( long long long str ) SteamAPI_ISteamMusicRemote_SetPlaylistEntry_
374 cdecl SteamAPI_ISteamMusicRemote_SetQueueEntry( long long long str ) SteamAPI_ISteamMusicRemote_SetQueueEntry_
375 cdecl SteamAPI_ISteamMusicRemote_UpdateCurrentEntryCoverArt( long ptr long ) SteamAPI_ISteamMusicRemote_UpdateCurrentEntryCoverArt_
376 cdecl SteamAPI_ISteamMusicRemote_UpdateCurrentEntryElapsedSeconds( long long ) SteamAPI_ISteamMusicRemote_UpdateCurrentEntryElapsedSeconds_
377 cdecl SteamAPI_ISteamMusicRemote_UpdateCurrentEntryText( long str ) SteamAPI_ISteamMusicRemote_UpdateCurrentEntryText_
378 cdecl SteamAPI_ISteamMusicRemote_UpdateLooped( long long ) SteamAPI_ISteamMusicRemote_UpdateLooped_
379 cdecl SteamAPI_ISteamMusicRemote_UpdatePlaybackStatus( long long ) SteamAPI_ISteamMusicRemote_UpdatePlaybackStatus_
380 cdecl SteamAPI_ISteamMusicRemote_UpdateShuffled( long long ) SteamAPI_ISteamMusicRemote_UpdateShuffled_
381 cdecl SteamAPI_ISteamMusicRemote_UpdateVolume( long long ) SteamAPI_ISteamMusicRemote_UpdateVolume_
382 cdecl SteamAPI_ISteamMusic_BIsEnabled( long ) SteamAPI_ISteamMusic_BIsEnabled_
383 cdecl SteamAPI_ISteamMusic_BIsPlaying( long ) SteamAPI_ISteamMusic_BIsPlaying_
384 cdecl SteamAPI_ISteamMusic_GetPlaybackStatus( long ) SteamAPI_ISteamMusic_GetPlaybackStatus_
385 cdecl SteamAPI_ISteamMusic_GetVolume( long ) SteamAPI_ISteamMusic_GetVolume_
386 cdecl SteamAPI_ISteamMusic_Pause( long ) SteamAPI_ISteamMusic_Pause_
387 cdecl SteamAPI_ISteamMusic_Play( long ) SteamAPI_ISteamMusic_Play_
388 cdecl SteamAPI_ISteamMusic_PlayNext( long ) SteamAPI_ISteamMusic_PlayNext_
389 cdecl SteamAPI_ISteamMusic_PlayPrevious( long ) SteamAPI_ISteamMusic_PlayPrevious_
390 cdecl SteamAPI_ISteamMusic_SetVolume( long long ) SteamAPI_ISteamMusic_SetVolume_
391 cdecl SteamAPI_ISteamNetworking_AcceptP2PSessionWithUser( long long ) SteamAPI_ISteamNetworking_AcceptP2PSessionWithUser_
392 cdecl SteamAPI_ISteamNetworking_AllowP2PPacketRelay( long long ) SteamAPI_ISteamNetworking_AllowP2PPacketRelay_
393 cdecl SteamAPI_ISteamNetworking_CloseP2PChannelWithUser( long long long ) SteamAPI_ISteamNetworking_CloseP2PChannelWithUser_
394 cdecl SteamAPI_ISteamNetworking_CloseP2PSessionWithUser( long long ) SteamAPI_ISteamNetworking_CloseP2PSessionWithUser_
395 cdecl SteamAPI_ISteamNetworking_CreateConnectionSocket( long long long long ) SteamAPI_ISteamNetworking_CreateConnectionSocket_
396 cdecl SteamAPI_ISteamNetworking_CreateListenSocket( long long long long long ) SteamAPI_ISteamNetworking_CreateListenSocket_
397 cdecl SteamAPI_ISteamNetworking_CreateP2PConnectionSocket( long long long long long ) SteamAPI_ISteamNetworking_CreateP2PConnectionSocket_
398 cdecl SteamAPI_ISteamNetworking_DestroyListenSocket( long long long ) SteamAPI_ISteamNetworking_DestroyListenSocket_
399 cdecl SteamAPI_ISteamNetworking_DestroySocket( long long long ) SteamAPI_ISteamNetworking_DestroySocket_
400 cdecl SteamAPI_ISteamNetworking_GetListenSocketInfo( long long ptr ptr ) SteamAPI_ISteamNetworking_GetListenSocketInfo_
401 cdecl SteamAPI_ISteamNetworking_GetMaxPacketSize( long long ) SteamAPI_ISteamNetworking_GetMaxPacketSize_
402 cdecl SteamAPI_ISteamNetworking_GetP2PSessionState( long long ptr ) SteamAPI_ISteamNetworking_GetP2PSessionState_
403 cdecl SteamAPI_ISteamNetworking_GetSocketConnectionType( long long ) SteamAPI_ISteamNetworking_GetSocketConnectionType_
404 cdecl SteamAPI_ISteamNetworking_GetSocketInfo( long long ptr ptr ptr ptr ) SteamAPI_ISteamNetworking_GetSocketInfo_
405 cdecl SteamAPI_ISteamNetworking_IsDataAvailable( long long ptr ptr ) SteamAPI_ISteamNetworking_IsDataAvailable_
406 cdecl SteamAPI_ISteamNetworking_IsDataAvailableOnSocket( long long ptr ) SteamAPI_ISteamNetworking_IsDataAvailableOnSocket_
407 cdecl SteamAPI_ISteamNetworking_IsP2PPacketAvailable( long ptr long ) SteamAPI_ISteamNetworking_IsP2PPacketAvailable_
408 cdecl SteamAPI_ISteamNetworking_ReadP2PPacket( long ptr long ptr ptr long ) SteamAPI_ISteamNetworking_ReadP2PPacket_
409 cdecl SteamAPI_ISteamNetworking_RetrieveData( long long ptr long ptr ptr ) SteamAPI_ISteamNetworking_RetrieveData_
410 cdecl SteamAPI_ISteamNetworking_RetrieveDataFromSocket( long long ptr long ptr ) SteamAPI_ISteamNetworking_RetrieveDataFromSocket_
411 cdecl SteamAPI_ISteamNetworking_SendDataOnSocket( long long ptr long long ) SteamAPI_ISteamNetworking_SendDataOnSocket_
412 cdecl SteamAPI_ISteamNetworking_SendP2PPacket( long long ptr long long long ) SteamAPI_ISteamNetworking_SendP2PPacket_
413 cdecl SteamAPI_ISteamRemoteStorage_CommitPublishedFileUpdate( long long ) SteamAPI_ISteamRemoteStorage_CommitPublishedFileUpdate_
414 cdecl SteamAPI_ISteamRemoteStorage_CreatePublishedFileUpdateRequest( long long ) SteamAPI_ISteamRemoteStorage_CreatePublishedFileUpdateRequest_
415 cdecl SteamAPI_ISteamRemoteStorage_DeletePublishedFile( long long ) SteamAPI_ISteamRemoteStorage_DeletePublishedFile_
416 cdecl SteamAPI_ISteamRemoteStorage_EnumeratePublishedFilesByUserAction( long long long ) SteamAPI_ISteamRemoteStorage_EnumeratePublishedFilesByUserAction_
417 cdecl SteamAPI_ISteamRemoteStorage_EnumeratePublishedWorkshopFiles( long long long long long ptr ptr ) SteamAPI_ISteamRemoteStorage_EnumeratePublishedWorkshopFiles_
418 cdecl SteamAPI_ISteamRemoteStorage_EnumerateUserPublishedFiles( long long ) SteamAPI_ISteamRemoteStorage_EnumerateUserPublishedFiles_
419 cdecl SteamAPI_ISteamRemoteStorage_EnumerateUserSharedWorkshopFiles( long long long ptr ptr ) SteamAPI_ISteamRemoteStorage_EnumerateUserSharedWorkshopFiles_
420 cdecl SteamAPI_ISteamRemoteStorage_EnumerateUserSubscribedFiles( long long ) SteamAPI_ISteamRemoteStorage_EnumerateUserSubscribedFiles_
421 cdecl SteamAPI_ISteamRemoteStorage_FileDelete( long str ) SteamAPI_ISteamRemoteStorage_FileDelete_
422 cdecl SteamAPI_ISteamRemoteStorage_FileExists( long str ) SteamAPI_ISteamRemoteStorage_FileExists_
423 cdecl SteamAPI_ISteamRemoteStorage_FileForget( long str ) SteamAPI_ISteamRemoteStorage_FileForget_
424 cdecl SteamAPI_ISteamRemoteStorage_FilePersisted( long str ) SteamAPI_ISteamRemoteStorage_FilePersisted_
425 cdecl SteamAPI_ISteamRemoteStorage_FileRead( long str ptr long ) SteamAPI_ISteamRemoteStorage_FileRead_
426 cdecl SteamAPI_ISteamRemoteStorage_FileShare( long str ) SteamAPI_ISteamRemoteStorage_FileShare_
427 cdecl SteamAPI_ISteamRemoteStorage_FileWrite( long str ptr long ) SteamAPI_ISteamRemoteStorage_FileWrite_
428 cdecl SteamAPI_ISteamRemoteStorage_FileWriteStreamCancel( long long ) SteamAPI_ISteamRemoteStorage_FileWriteStreamCancel_
429 cdecl SteamAPI_ISteamRemoteStorage_FileWriteStreamClose( long long ) SteamAPI_ISteamRemoteStorage_FileWriteStreamClose_
430 cdecl SteamAPI_ISteamRemoteStorage_FileWriteStreamOpen( long str ) SteamAPI_ISteamRemoteStorage_FileWriteStreamOpen_
431 cdecl SteamAPI_ISteamRemoteStorage_FileWriteStreamWriteChunk( long long ptr long ) SteamAPI_ISteamRemoteStorage_FileWriteStreamWriteChunk_
432 cdecl SteamAPI_ISteamRemoteStorage_GetCachedUGCCount( long ) SteamAPI_ISteamRemoteStorage_GetCachedUGCCount_
433 cdecl SteamAPI_ISteamRemoteStorage_GetCachedUGCHandle( long long ) SteamAPI_ISteamRemoteStorage_GetCachedUGCHandle_
434 cdecl SteamAPI_ISteamRemoteStorage_GetFileCount( long ) SteamAPI_ISteamRemoteStorage_GetFileCount_
435 cdecl SteamAPI_ISteamRemoteStorage_GetFileNameAndSize( long long ptr ) SteamAPI_ISteamRemoteStorage_GetFileNameAndSize_
436 cdecl SteamAPI_ISteamRemoteStorage_GetFileSize( long str ) SteamAPI_ISteamRemoteStorage_GetFileSize_
437 cdecl SteamAPI_ISteamRemoteStorage_GetFileTimestamp( long str ) SteamAPI_ISteamRemoteStorage_GetFileTimestamp_
438 cdecl SteamAPI_ISteamRemoteStorage_GetPublishedFileDetails( long long long ) SteamAPI_ISteamRemoteStorage_GetPublishedFileDetails_
439 cdecl SteamAPI_ISteamRemoteStorage_GetPublishedItemVoteDetails( long long ) SteamAPI_ISteamRemoteStorage_GetPublishedItemVoteDetails_
440 cdecl SteamAPI_ISteamRemoteStorage_GetQuota( long ptr ptr ) SteamAPI_ISteamRemoteStorage_GetQuota_
441 cdecl SteamAPI_ISteamRemoteStorage_GetSyncPlatforms( long str ) SteamAPI_ISteamRemoteStorage_GetSyncPlatforms_
442 cdecl SteamAPI_ISteamRemoteStorage_GetUGCDetails( long long ptr ptr ptr ptr ) SteamAPI_ISteamRemoteStorage_GetUGCDetails_
443 cdecl SteamAPI_ISteamRemoteStorage_GetUGCDownloadProgress( long long ptr ptr ) SteamAPI_ISteamRemoteStorage_GetUGCDownloadProgress_
444 cdecl SteamAPI_ISteamRemoteStorage_GetUserPublishedItemVoteDetails( long long ) SteamAPI_ISteamRemoteStorage_GetUserPublishedItemVoteDetails_
445 cdecl SteamAPI_ISteamRemoteStorage_IsCloudEnabledForAccount( long ) SteamAPI_ISteamRemoteStorage_IsCloudEnabledForAccount_
446 cdecl SteamAPI_ISteamRemoteStorage_IsCloudEnabledForApp( long ) SteamAPI_ISteamRemoteStorage_IsCloudEnabledForApp_
447 cdecl SteamAPI_ISteamRemoteStorage_PublishVideo( long long str str str long str str long ptr ) SteamAPI_ISteamRemoteStorage_PublishVideo_
448 cdecl SteamAPI_ISteamRemoteStorage_PublishWorkshopFile( long str str long str str long ptr long ) SteamAPI_ISteamRemoteStorage_PublishWorkshopFile_
449 cdecl SteamAPI_ISteamRemoteStorage_SetCloudEnabledForApp( long long ) SteamAPI_ISteamRemoteStorage_SetCloudEnabledForApp_
450 cdecl SteamAPI_ISteamRemoteStorage_SetSyncPlatforms( long str long ) SteamAPI_ISteamRemoteStorage_SetSyncPlatforms_
451 cdecl SteamAPI_ISteamRemoteStorage_SetUserPublishedFileAction( long long long ) SteamAPI_ISteamRemoteStorage_SetUserPublishedFileAction_
452 cdecl SteamAPI_ISteamRemoteStorage_SubscribePublishedFile( long long ) SteamAPI_ISteamRemoteStorage_SubscribePublishedFile_
453 cdecl SteamAPI_ISteamRemoteStorage_UGCDownload( long long long ) SteamAPI_ISteamRemoteStorage_UGCDownload_
454 cdecl SteamAPI_ISteamRemoteStorage_UGCDownloadToLocation( long long str long ) SteamAPI_ISteamRemoteStorage_UGCDownloadToLocation_
455 cdecl SteamAPI_ISteamRemoteStorage_UGCRead( long long ptr long long long ) SteamAPI_ISteamRemoteStorage_UGCRead_
456 cdecl SteamAPI_ISteamRemoteStorage_UnsubscribePublishedFile( long long ) SteamAPI_ISteamRemoteStorage_UnsubscribePublishedFile_
457 cdecl SteamAPI_ISteamRemoteStorage_UpdatePublishedFileDescription( long long str ) SteamAPI_ISteamRemoteStorage_UpdatePublishedFileDescription_
458 cdecl SteamAPI_ISteamRemoteStorage_UpdatePublishedFileFile( long long str ) SteamAPI_ISteamRemoteStorage_UpdatePublishedFileFile_
459 cdecl SteamAPI_ISteamRemoteStorage_UpdatePublishedFilePreviewFile( long long str ) SteamAPI_ISteamRemoteStorage_UpdatePublishedFilePreviewFile_
460 cdecl SteamAPI_ISteamRemoteStorage_UpdatePublishedFileSetChangeDescription( long long str ) SteamAPI_ISteamRemoteStorage_UpdatePublishedFileSetChangeDescription_
461 cdecl SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTags( long long ptr ) SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTags_
462 cdecl SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTitle( long long str ) SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTitle_
463 cdecl SteamAPI_ISteamRemoteStorage_UpdatePublishedFileVisibility( long long long ) SteamAPI_ISteamRemoteStorage_UpdatePublishedFileVisibility_
464 cdecl SteamAPI_ISteamRemoteStorage_UpdateUserPublishedItemVote( long long long ) SteamAPI_ISteamRemoteStorage_UpdateUserPublishedItemVote_
465 cdecl SteamAPI_ISteamScreenshots_AddScreenshotToLibrary( long str str long long ) SteamAPI_ISteamScreenshots_AddScreenshotToLibrary_
466 cdecl SteamAPI_ISteamScreenshots_HookScreenshots( long long ) SteamAPI_ISteamScreenshots_HookScreenshots_
467 cdecl SteamAPI_ISteamScreenshots_SetLocation( long long str ) SteamAPI_ISteamScreenshots_SetLocation_
468 cdecl SteamAPI_ISteamScreenshots_TagPublishedFile( long long long ) SteamAPI_ISteamScreenshots_TagPublishedFile_
469 cdecl SteamAPI_ISteamScreenshots_TagUser( long long long ) SteamAPI_ISteamScreenshots_TagUser_
470 cdecl SteamAPI_ISteamScreenshots_TriggerScreenshot( long ) SteamAPI_ISteamScreenshots_TriggerScreenshot_
471 cdecl SteamAPI_ISteamScreenshots_WriteScreenshot( long ptr long long long ) SteamAPI_ISteamScreenshots_WriteScreenshot_
472 cdecl SteamAPI_ISteamUGC_AddExcludedTag( long long str ) SteamAPI_ISteamUGC_AddExcludedTag_
473 cdecl SteamAPI_ISteamUGC_AddItemToFavorites( long long long ) SteamAPI_ISteamUGC_AddItemToFavorites_
474 cdecl SteamAPI_ISteamUGC_AddRequiredTag( long long str ) SteamAPI_ISteamUGC_AddRequiredTag_
475 cdecl SteamAPI_ISteamUGC_CreateItem( long long long ) SteamAPI_ISteamUGC_CreateItem_
476 cdecl SteamAPI_ISteamUGC_CreateQueryAllUGCRequest( long long long long long long ) SteamAPI_ISteamUGC_CreateQueryAllUGCRequest_
477 cdecl SteamAPI_ISteamUGC_CreateQueryUGCDetailsRequest( long ptr long ) SteamAPI_ISteamUGC_CreateQueryUGCDetailsRequest_
478 cdecl SteamAPI_ISteamUGC_CreateQueryUserUGCRequest( long long long long long long long long ) SteamAPI_ISteamUGC_CreateQueryUserUGCRequest_
479 cdecl SteamAPI_ISteamUGC_DownloadItem( long long long ) SteamAPI_ISteamUGC_DownloadItem_
480 cdecl SteamAPI_ISteamUGC_GetItemDownloadInfo( long long ptr ptr ) SteamAPI_ISteamUGC_GetItemDownloadInfo_
481 cdecl SteamAPI_ISteamUGC_GetItemInstallInfo( long long ptr str long ptr ) SteamAPI_ISteamUGC_GetItemInstallInfo_
482 cdecl SteamAPI_ISteamUGC_GetItemState( long long ) SteamAPI_ISteamUGC_GetItemState_
483 cdecl SteamAPI_ISteamUGC_GetItemUpdateProgress( long long ptr ptr ) SteamAPI_ISteamUGC_GetItemUpdateProgress_
484 cdecl SteamAPI_ISteamUGC_GetNumSubscribedItems( long ) SteamAPI_ISteamUGC_GetNumSubscribedItems_
485 cdecl SteamAPI_ISteamUGC_GetQueryUGCAdditionalPreview( long long long long str long str long ptr ) SteamAPI_ISteamUGC_GetQueryUGCAdditionalPreview_
486 cdecl SteamAPI_ISteamUGC_GetQueryUGCChildren( long long long ptr long ) SteamAPI_ISteamUGC_GetQueryUGCChildren_
487 cdecl SteamAPI_ISteamUGC_GetQueryUGCMetadata( long long long str long ) SteamAPI_ISteamUGC_GetQueryUGCMetadata_
488 cdecl SteamAPI_ISteamUGC_GetQueryUGCNumAdditionalPreviews( long long long ) SteamAPI_ISteamUGC_GetQueryUGCNumAdditionalPreviews_
489 cdecl SteamAPI_ISteamUGC_GetQueryUGCPreviewURL( long long long str long ) SteamAPI_ISteamUGC_GetQueryUGCPreviewURL_
490 cdecl SteamAPI_ISteamUGC_GetQueryUGCResult( long long long ptr ) SteamAPI_ISteamUGC_GetQueryUGCResult_
491 cdecl SteamAPI_ISteamUGC_GetQueryUGCStatistic( long long long long ptr ) SteamAPI_ISteamUGC_GetQueryUGCStatistic_
492 cdecl SteamAPI_ISteamUGC_GetSubscribedItems( long ptr long ) SteamAPI_ISteamUGC_GetSubscribedItems_
493 cdecl SteamAPI_ISteamUGC_ReleaseQueryUGCRequest( long long ) SteamAPI_ISteamUGC_ReleaseQueryUGCRequest_
494 cdecl SteamAPI_ISteamUGC_RemoveItemFromFavorites( long long long ) SteamAPI_ISteamUGC_RemoveItemFromFavorites_
495 cdecl SteamAPI_ISteamUGC_RequestUGCDetails( long long long ) SteamAPI_ISteamUGC_RequestUGCDetails_
496 cdecl SteamAPI_ISteamUGC_SendQueryUGCRequest( long long ) SteamAPI_ISteamUGC_SendQueryUGCRequest_
497 cdecl SteamAPI_ISteamUGC_SetAllowCachedResponse( long long long ) SteamAPI_ISteamUGC_SetAllowCachedResponse_
498 cdecl SteamAPI_ISteamUGC_SetCloudFileNameFilter( long long str ) SteamAPI_ISteamUGC_SetCloudFileNameFilter_
499 cdecl SteamAPI_ISteamUGC_SetItemContent( long long str ) SteamAPI_ISteamUGC_SetItemContent_
500 cdecl SteamAPI_ISteamUGC_SetItemDescription( long long str ) SteamAPI_ISteamUGC_SetItemDescription_
501 cdecl SteamAPI_ISteamUGC_SetItemMetadata( long long str ) SteamAPI_ISteamUGC_SetItemMetadata_
502 cdecl SteamAPI_ISteamUGC_SetItemPreview( long long str ) SteamAPI_ISteamUGC_SetItemPreview_
503 cdecl SteamAPI_ISteamUGC_SetItemTags( long long ptr ) SteamAPI_ISteamUGC_SetItemTags_
504 cdecl SteamAPI_ISteamUGC_SetItemTitle( long long str ) SteamAPI_ISteamUGC_SetItemTitle_
505 cdecl SteamAPI_ISteamUGC_SetItemVisibility( long long long ) SteamAPI_ISteamUGC_SetItemVisibility_
506 cdecl SteamAPI_ISteamUGC_SetMatchAnyTag( long long long ) SteamAPI_ISteamUGC_SetMatchAnyTag_
507 cdecl SteamAPI_ISteamUGC_SetRankedByTrendDays( long long long ) SteamAPI_ISteamUGC_SetRankedByTrendDays_
508 cdecl SteamAPI_ISteamUGC_SetReturnAdditionalPreviews( long long long ) SteamAPI_ISteamUGC_SetReturnAdditionalPreviews_
509 cdecl SteamAPI_ISteamUGC_SetReturnChildren( long long long ) SteamAPI_ISteamUGC_SetReturnChildren_
510 cdecl SteamAPI_ISteamUGC_SetReturnLongDescription( long long long ) SteamAPI_ISteamUGC_SetReturnLongDescription_
511 cdecl SteamAPI_ISteamUGC_SetReturnMetadata( long long long ) SteamAPI_ISteamUGC_SetReturnMetadata_
512 cdecl SteamAPI_ISteamUGC_SetReturnTotalOnly( long long long ) SteamAPI_ISteamUGC_SetReturnTotalOnly_
513 cdecl SteamAPI_ISteamUGC_SetSearchText( long long str ) SteamAPI_ISteamUGC_SetSearchText_
514 cdecl SteamAPI_ISteamUGC_StartItemUpdate( long long long ) SteamAPI_ISteamUGC_StartItemUpdate_
515 cdecl SteamAPI_ISteamUGC_SubmitItemUpdate( long long str ) SteamAPI_ISteamUGC_SubmitItemUpdate_
516 cdecl SteamAPI_ISteamUGC_SubscribeItem( long long ) SteamAPI_ISteamUGC_SubscribeItem_
517 cdecl SteamAPI_ISteamUGC_UnsubscribeItem( long long ) SteamAPI_ISteamUGC_UnsubscribeItem_
518 cdecl SteamAPI_ISteamUnifiedMessages_GetMethodResponseData( long long ptr long long ) SteamAPI_ISteamUnifiedMessages_GetMethodResponseData_
519 cdecl SteamAPI_ISteamUnifiedMessages_GetMethodResponseInfo( long long ptr ptr ) SteamAPI_ISteamUnifiedMessages_GetMethodResponseInfo_
520 cdecl SteamAPI_ISteamUnifiedMessages_ReleaseMethod( long long ) SteamAPI_ISteamUnifiedMessages_ReleaseMethod_
521 cdecl SteamAPI_ISteamUnifiedMessages_SendMethod( long str ptr long long ) SteamAPI_ISteamUnifiedMessages_SendMethod_
522 cdecl SteamAPI_ISteamUnifiedMessages_SendNotification( long str ptr long ) SteamAPI_ISteamUnifiedMessages_SendNotification_
523 cdecl SteamAPI_ISteamUserStats_AttachLeaderboardUGC( long long long ) SteamAPI_ISteamUserStats_AttachLeaderboardUGC_
524 cdecl SteamAPI_ISteamUserStats_ClearAchievement( long str ) SteamAPI_ISteamUserStats_ClearAchievement_
525 cdecl SteamAPI_ISteamUserStats_DownloadLeaderboardEntries( long long long long long ) SteamAPI_ISteamUserStats_DownloadLeaderboardEntries_
526 cdecl SteamAPI_ISteamUserStats_DownloadLeaderboardEntriesForUsers( long long ptr long ) SteamAPI_ISteamUserStats_DownloadLeaderboardEntriesForUsers_
527 cdecl SteamAPI_ISteamUserStats_FindLeaderboard( long str ) SteamAPI_ISteamUserStats_FindLeaderboard_
528 cdecl SteamAPI_ISteamUserStats_FindOrCreateLeaderboard( long str long long ) SteamAPI_ISteamUserStats_FindOrCreateLeaderboard_
529 cdecl SteamAPI_ISteamUserStats_GetAchievement( long str ptr ) SteamAPI_ISteamUserStats_GetAchievement_
530 cdecl SteamAPI_ISteamUserStats_GetAchievementAchievedPercent( long str ptr ) SteamAPI_ISteamUserStats_GetAchievementAchievedPercent_
531 cdecl SteamAPI_ISteamUserStats_GetAchievementAndUnlockTime( long str ptr ptr ) SteamAPI_ISteamUserStats_GetAchievementAndUnlockTime_
532 cdecl SteamAPI_ISteamUserStats_GetAchievementDisplayAttribute( long str str ) SteamAPI_ISteamUserStats_GetAchievementDisplayAttribute_
533 cdecl SteamAPI_ISteamUserStats_GetAchievementIcon( long str ) SteamAPI_ISteamUserStats_GetAchievementIcon_
534 cdecl SteamAPI_ISteamUserStats_GetAchievementName( long long ) SteamAPI_ISteamUserStats_GetAchievementName_
535 cdecl SteamAPI_ISteamUserStats_GetDownloadedLeaderboardEntry( long long long ptr ptr long ) SteamAPI_ISteamUserStats_GetDownloadedLeaderboardEntry_
536 cdecl SteamAPI_ISteamUserStats_GetGlobalStat( long str ptr ) SteamAPI_ISteamUserStats_GetGlobalStat_
537 cdecl SteamAPI_ISteamUserStats_GetGlobalStat0( long str ptr ) SteamAPI_ISteamUserStats_GetGlobalStat0_
538 cdecl SteamAPI_ISteamUserStats_GetGlobalStatHistory( long str ptr long ) SteamAPI_ISteamUserStats_GetGlobalStatHistory_
539 cdecl SteamAPI_ISteamUserStats_GetGlobalStatHistory0( long str ptr long ) SteamAPI_ISteamUserStats_GetGlobalStatHistory0_
540 cdecl SteamAPI_ISteamUserStats_GetLeaderboardDisplayType( long long ) SteamAPI_ISteamUserStats_GetLeaderboardDisplayType_
541 cdecl SteamAPI_ISteamUserStats_GetLeaderboardEntryCount( long long ) SteamAPI_ISteamUserStats_GetLeaderboardEntryCount_
542 cdecl SteamAPI_ISteamUserStats_GetLeaderboardName( long long ) SteamAPI_ISteamUserStats_GetLeaderboardName_
543 cdecl SteamAPI_ISteamUserStats_GetLeaderboardSortMethod( long long ) SteamAPI_ISteamUserStats_GetLeaderboardSortMethod_
544 cdecl SteamAPI_ISteamUserStats_GetMostAchievedAchievementInfo( long str long ptr ptr ) SteamAPI_ISteamUserStats_GetMostAchievedAchievementInfo_
545 cdecl SteamAPI_ISteamUserStats_GetNextMostAchievedAchievementInfo( long long str long ptr ptr ) SteamAPI_ISteamUserStats_GetNextMostAchievedAchievementInfo_
546 cdecl SteamAPI_ISteamUserStats_GetNumAchievements( long ) SteamAPI_ISteamUserStats_GetNumAchievements_
547 cdecl SteamAPI_ISteamUserStats_GetNumberOfCurrentPlayers( long ) SteamAPI_ISteamUserStats_GetNumberOfCurrentPlayers_
548 cdecl SteamAPI_ISteamUserStats_GetStat( long str ptr ) SteamAPI_ISteamUserStats_GetStat_
549 cdecl SteamAPI_ISteamUserStats_GetStat0( long str ptr ) SteamAPI_ISteamUserStats_GetStat0_
550 cdecl SteamAPI_ISteamUserStats_GetUserAchievement( long long str ptr ) SteamAPI_ISteamUserStats_GetUserAchievement_
551 cdecl SteamAPI_ISteamUserStats_GetUserAchievementAndUnlockTime( long long str ptr ptr ) SteamAPI_ISteamUserStats_GetUserAchievementAndUnlockTime_
552 cdecl SteamAPI_ISteamUserStats_GetUserStat( long long str ptr ) SteamAPI_ISteamUserStats_GetUserStat_
553 cdecl SteamAPI_ISteamUserStats_GetUserStat0( long long str ptr ) SteamAPI_ISteamUserStats_GetUserStat0_
554 cdecl SteamAPI_ISteamUserStats_IndicateAchievementProgress( long str long long ) SteamAPI_ISteamUserStats_IndicateAchievementProgress_
555 cdecl SteamAPI_ISteamUserStats_RequestCurrentStats( long ) SteamAPI_ISteamUserStats_RequestCurrentStats_
556 cdecl SteamAPI_ISteamUserStats_RequestGlobalAchievementPercentages( long ) SteamAPI_ISteamUserStats_RequestGlobalAchievementPercentages_
557 cdecl SteamAPI_ISteamUserStats_RequestGlobalStats( long long ) SteamAPI_ISteamUserStats_RequestGlobalStats_
558 cdecl SteamAPI_ISteamUserStats_RequestUserStats( long long ) SteamAPI_ISteamUserStats_RequestUserStats_
559 cdecl SteamAPI_ISteamUserStats_ResetAllStats( long long ) SteamAPI_ISteamUserStats_ResetAllStats_
560 cdecl SteamAPI_ISteamUserStats_SetAchievement( long str ) SteamAPI_ISteamUserStats_SetAchievement_
561 cdecl SteamAPI_ISteamUserStats_SetStat( long str long ) SteamAPI_ISteamUserStats_SetStat_
562 cdecl SteamAPI_ISteamUserStats_SetStat0( long str long ) SteamAPI_ISteamUserStats_SetStat0_
563 cdecl SteamAPI_ISteamUserStats_StoreStats( long ) SteamAPI_ISteamUserStats_StoreStats_
564 cdecl SteamAPI_ISteamUserStats_UpdateAvgRateStat( long str long long ) SteamAPI_ISteamUserStats_UpdateAvgRateStat_
565 cdecl SteamAPI_ISteamUserStats_UploadLeaderboardScore( long long long long ptr long ) SteamAPI_ISteamUserStats_UploadLeaderboardScore_
566 cdecl SteamAPI_ISteamUser_AdvertiseGame( long long long long ) SteamAPI_ISteamUser_AdvertiseGame_
567 cdecl SteamAPI_ISteamUser_BIsBehindNAT( long ) SteamAPI_ISteamUser_BIsBehindNAT_
568 cdecl SteamAPI_ISteamUser_BLoggedOn( long ) SteamAPI_ISteamUser_BLoggedOn_
569 cdecl SteamAPI_ISteamUser_BeginAuthSession( long ptr long long ) SteamAPI_ISteamUser_BeginAuthSession_
570 cdecl SteamAPI_ISteamUser_CancelAuthTicket( long long ) SteamAPI_ISteamUser_CancelAuthTicket_
571 cdecl SteamAPI_ISteamUser_DecompressVoice( long ptr long ptr long ptr long ) SteamAPI_ISteamUser_DecompressVoice_
572 cdecl SteamAPI_ISteamUser_EndAuthSession( long long ) SteamAPI_ISteamUser_EndAuthSession_
573 cdecl SteamAPI_ISteamUser_GetAuthSessionTicket( long ptr long ptr ) SteamAPI_ISteamUser_GetAuthSessionTicket_
574 cdecl SteamAPI_ISteamUser_GetAvailableVoice( long ptr ptr long ) SteamAPI_ISteamUser_GetAvailableVoice_
575 cdecl SteamAPI_ISteamUser_GetEncryptedAppTicket( long ptr long ptr ) SteamAPI_ISteamUser_GetEncryptedAppTicket_
576 cdecl SteamAPI_ISteamUser_GetGameBadgeLevel( long long long ) SteamAPI_ISteamUser_GetGameBadgeLevel_
577 cdecl SteamAPI_ISteamUser_GetHSteamUser( long ) SteamAPI_ISteamUser_GetHSteamUser_
578 cdecl SteamAPI_ISteamUser_GetPlayerSteamLevel( long ) SteamAPI_ISteamUser_GetPlayerSteamLevel_
579 cdecl SteamAPI_ISteamUser_GetSteamID( long ) SteamAPI_ISteamUser_GetSteamID_
580 cdecl SteamAPI_ISteamUser_GetUserDataFolder( long str long ) SteamAPI_ISteamUser_GetUserDataFolder_
581 cdecl SteamAPI_ISteamUser_GetVoice( long long ptr long ptr long ptr long ptr long ) SteamAPI_ISteamUser_GetVoice_
582 cdecl SteamAPI_ISteamUser_GetVoiceOptimalSampleRate( long ) SteamAPI_ISteamUser_GetVoiceOptimalSampleRate_
583 cdecl SteamAPI_ISteamUser_InitiateGameConnection( long ptr long long long long long ) SteamAPI_ISteamUser_InitiateGameConnection_
584 cdecl SteamAPI_ISteamUser_RequestEncryptedAppTicket( long ptr long ) SteamAPI_ISteamUser_RequestEncryptedAppTicket_
585 cdecl SteamAPI_ISteamUser_RequestStoreAuthURL( long str ) SteamAPI_ISteamUser_RequestStoreAuthURL_
586 cdecl SteamAPI_ISteamUser_StartVoiceRecording( long ) SteamAPI_ISteamUser_StartVoiceRecording_
587 cdecl SteamAPI_ISteamUser_StopVoiceRecording( long ) SteamAPI_ISteamUser_StopVoiceRecording_
588 cdecl SteamAPI_ISteamUser_TerminateGameConnection( long long long ) SteamAPI_ISteamUser_TerminateGameConnection_
589 cdecl SteamAPI_ISteamUser_TrackAppUsageEvent( long long long str ) SteamAPI_ISteamUser_TrackAppUsageEvent_
590 cdecl SteamAPI_ISteamUser_UserHasLicenseForApp( long long long ) SteamAPI_ISteamUser_UserHasLicenseForApp_
591 cdecl SteamAPI_ISteamUtils_BOverlayNeedsPresent( long ) SteamAPI_ISteamUtils_BOverlayNeedsPresent_
592 cdecl SteamAPI_ISteamUtils_CheckFileSignature( long str ) SteamAPI_ISteamUtils_CheckFileSignature_
593 cdecl SteamAPI_ISteamUtils_GetAPICallFailureReason( long long ) SteamAPI_ISteamUtils_GetAPICallFailureReason_
594 cdecl SteamAPI_ISteamUtils_GetAPICallResult( long long ptr long long ptr ) SteamAPI_ISteamUtils_GetAPICallResult_
595 cdecl SteamAPI_ISteamUtils_GetAppID( long ) SteamAPI_ISteamUtils_GetAppID_
596 cdecl SteamAPI_ISteamUtils_GetCSERIPPort( long ptr ptr ) SteamAPI_ISteamUtils_GetCSERIPPort_
597 cdecl SteamAPI_ISteamUtils_GetConnectedUniverse( long ) SteamAPI_ISteamUtils_GetConnectedUniverse_
598 cdecl SteamAPI_ISteamUtils_GetCurrentBatteryPower( long ) SteamAPI_ISteamUtils_GetCurrentBatteryPower_
599 cdecl SteamAPI_ISteamUtils_GetEnteredGamepadTextInput( long str long ) SteamAPI_ISteamUtils_GetEnteredGamepadTextInput_
600 cdecl SteamAPI_ISteamUtils_GetEnteredGamepadTextLength( long ) SteamAPI_ISteamUtils_GetEnteredGamepadTextLength_
601 cdecl SteamAPI_ISteamUtils_GetIPCCallCount( long ) SteamAPI_ISteamUtils_GetIPCCallCount_
602 cdecl SteamAPI_ISteamUtils_GetIPCountry( long ) SteamAPI_ISteamUtils_GetIPCountry_
603 cdecl SteamAPI_ISteamUtils_GetImageRGBA( long long ptr long ) SteamAPI_ISteamUtils_GetImageRGBA_
604 cdecl SteamAPI_ISteamUtils_GetImageSize( long long ptr ptr ) SteamAPI_ISteamUtils_GetImageSize_
605 cdecl SteamAPI_ISteamUtils_GetSecondsSinceAppActive( long ) SteamAPI_ISteamUtils_GetSecondsSinceAppActive_
606 cdecl SteamAPI_ISteamUtils_GetSecondsSinceComputerActive( long ) SteamAPI_ISteamUtils_GetSecondsSinceComputerActive_
607 cdecl SteamAPI_ISteamUtils_GetServerRealTime( long ) SteamAPI_ISteamUtils_GetServerRealTime_
608 cdecl SteamAPI_ISteamUtils_GetSteamUILanguage( long ) SteamAPI_ISteamUtils_GetSteamUILanguage_
609 cdecl SteamAPI_ISteamUtils_IsAPICallCompleted( long long ptr ) SteamAPI_ISteamUtils_IsAPICallCompleted_
610 cdecl SteamAPI_ISteamUtils_IsOverlayEnabled( long ) SteamAPI_ISteamUtils_IsOverlayEnabled_
611 cdecl SteamAPI_ISteamUtils_IsSteamRunningInVR( long ) SteamAPI_ISteamUtils_IsSteamRunningInVR_
612 stub SteamAPI_ISteamUtils_RunFrame() 
613 cdecl SteamAPI_ISteamUtils_SetOverlayNotificationPosition( long long ) SteamAPI_ISteamUtils_SetOverlayNotificationPosition_
614 cdecl SteamAPI_ISteamUtils_SetWarningMessageHook( long long ) SteamAPI_ISteamUtils_SetWarningMessageHook_
615 cdecl SteamAPI_ISteamUtils_ShowGamepadTextInput( long long long str long str ) SteamAPI_ISteamUtils_ShowGamepadTextInput_
616 cdecl SteamAPI_ISteamVideo_GetVideoURL( long long ) SteamAPI_ISteamVideo_GetVideoURL_
617 cdecl SteamAPI_ISteamVideo_IsBroadcasting( long ptr ) SteamAPI_ISteamVideo_IsBroadcasting_
618 cdecl SteamAPI_Init() SteamAPI_Init_
619 cdecl SteamAPI_InitSafe() SteamAPI_InitSafe_
620 cdecl SteamAPI_IsSteamRunning() SteamAPI_IsSteamRunning_
621 cdecl SteamAPI_RegisterCallResult( ptr long ) SteamAPI_RegisterCallResult_
622 cdecl SteamAPI_RegisterCallback( ptr long ) SteamAPI_RegisterCallback_
623 cdecl SteamAPI_RestartAppIfNecessary( long ) SteamAPI_RestartAppIfNecessary_
624 cdecl SteamAPI_RunCallbacks() SteamAPI_RunCallbacks_
625 cdecl SteamAPI_SetBreakpadAppID( long ) SteamAPI_SetBreakpadAppID_
626 cdecl SteamAPI_SetMiniDumpComment( str ) SteamAPI_SetMiniDumpComment_
627 cdecl SteamAPI_SetTryCatchCallbacks( long ) SteamAPI_SetTryCatchCallbacks_
628 cdecl SteamAPI_Shutdown() SteamAPI_Shutdown_
629 cdecl SteamAPI_UnregisterCallResult( ptr ) SteamAPI_UnregisterCallResult_
630 cdecl SteamAPI_UnregisterCallback( ptr ) SteamAPI_UnregisterCallback_
631 cdecl SteamAPI_UseBreakpadCrashHandler( ptr ptr ptr long ptr long ) SteamAPI_UseBreakpadCrashHandler_
632 cdecl SteamAPI_WriteMiniDump( long ptr long ) SteamAPI_WriteMiniDump_
633 stub SteamAPI_vr_IVRChaperone_GetCalibrationState() 
634 stub SteamAPI_vr_IVRChaperone_GetHardBoundsInfo() 
635 stub SteamAPI_vr_IVRChaperone_GetSeatedBoundsInfo() 
636 stub SteamAPI_vr_IVRChaperone_GetSoftBoundsInfo() 
637 stub SteamAPI_vr_IVRCompositor_ClearLastSubmittedFrame() 
638 stub SteamAPI_vr_IVRCompositor_ClearOverlay() 
639 stub SteamAPI_vr_IVRCompositor_CompositorBringToFront() 
640 stub SteamAPI_vr_IVRCompositor_CompositorGoToBack() 
641 stub SteamAPI_vr_IVRCompositor_CompositorQuit() 
642 stub SteamAPI_vr_IVRCompositor_FadeGrid() 
643 stub SteamAPI_vr_IVRCompositor_FadeToColor() 
644 stub SteamAPI_vr_IVRCompositor_GetFrameTiming() 
645 stub SteamAPI_vr_IVRCompositor_GetGamma() 
646 stub SteamAPI_vr_IVRCompositor_GetLastError() 
647 stub SteamAPI_vr_IVRCompositor_GetOverlayDefaults() 
648 stub SteamAPI_vr_IVRCompositor_GetVSync() 
649 stub SteamAPI_vr_IVRCompositor_IsFullscreen() 
650 stub SteamAPI_vr_IVRCompositor_SetGamma() 
651 stub SteamAPI_vr_IVRCompositor_SetGraphicsDevice() 
652 stub SteamAPI_vr_IVRCompositor_SetOverlay() 
653 stub SteamAPI_vr_IVRCompositor_SetOverlayFromFile() 
654 stub SteamAPI_vr_IVRCompositor_SetOverlayRaw() 
655 stub SteamAPI_vr_IVRCompositor_SetVSync() 
656 stub SteamAPI_vr_IVRCompositor_Submit() 
657 stub SteamAPI_vr_IVRCompositor_WaitGetPoses() 
658 stub SteamAPI_vr_IVRControlPanel_GetDriverCount() 
659 stub SteamAPI_vr_IVRControlPanel_GetDriverDisplayCount() 
660 stub SteamAPI_vr_IVRControlPanel_GetDriverDisplayId() 
661 stub SteamAPI_vr_IVRControlPanel_GetDriverDisplayModelNumber() 
662 stub SteamAPI_vr_IVRControlPanel_GetDriverDisplaySerialNumber() 
663 stub SteamAPI_vr_IVRControlPanel_GetDriverId() 
664 stub SteamAPI_vr_IVRControlPanel_GetIPD() 
665 stub SteamAPI_vr_IVRControlPanel_LoadSharedResource() 
666 stub SteamAPI_vr_IVRControlPanel_SetIPD() 
667 stub SteamAPI_vr_IVRSystem_AttachToWindow() 
668 stub SteamAPI_vr_IVRSystem_ComputeDistortion() 
669 stub SteamAPI_vr_IVRSystem_FreeRenderModel() 
670 stub SteamAPI_vr_IVRSystem_GetBoolTrackedDeviceProperty() 
671 stub SteamAPI_vr_IVRSystem_GetD3D9AdapterIndex() 
672 stub SteamAPI_vr_IVRSystem_GetDXGIOutputInfo() 
673 stub SteamAPI_vr_IVRSystem_GetDeviceToAbsoluteTrackingPose() 
674 stub SteamAPI_vr_IVRSystem_GetEventTypeNameFromEnum() 
675 stub SteamAPI_vr_IVRSystem_GetEyeOutputViewport() 
676 stub SteamAPI_vr_IVRSystem_GetEyeToHeadTransform() 
677 stub SteamAPI_vr_IVRSystem_GetFloatTrackedDeviceProperty() 
678 stub SteamAPI_vr_IVRSystem_GetHiddenAreaMesh() 
679 stub SteamAPI_vr_IVRSystem_GetInt32TrackedDeviceProperty() 
680 stub SteamAPI_vr_IVRSystem_GetMatrix34TrackedDeviceProperty() 
681 stub SteamAPI_vr_IVRSystem_GetProjectionMatrix() 
682 stub SteamAPI_vr_IVRSystem_GetProjectionRaw() 
683 stub SteamAPI_vr_IVRSystem_GetPropErrorNameFromEnum() 
684 stub SteamAPI_vr_IVRSystem_GetRecommendedRenderTargetSize() 
685 stub SteamAPI_vr_IVRSystem_GetSeatedZeroPoseToStandingAbsoluteTrackingPose() 
686 stub SteamAPI_vr_IVRSystem_GetStringTrackedDeviceProperty() 
687 stub SteamAPI_vr_IVRSystem_GetTimeSinceLastVsync() 
688 stub SteamAPI_vr_IVRSystem_GetTrackedDeviceClass() 
689 stub SteamAPI_vr_IVRSystem_GetUint64TrackedDeviceProperty() 
690 stub SteamAPI_vr_IVRSystem_GetWindowBounds() 
691 stub SteamAPI_vr_IVRSystem_IsTrackedDeviceConnected() 
692 stub SteamAPI_vr_IVRSystem_LoadRenderModel() 
693 stub SteamAPI_vr_IVRSystem_PollNextEvent() 
694 stub SteamAPI_vr_IVRSystem_ResetSeatedZeroPose() 
695 cdecl SteamAppList() SteamAppList_
696 cdecl SteamApps() SteamApps_
697 cdecl SteamClient() SteamClient_
698 cdecl SteamController() SteamController_
699 stub SteamController_GetControllerState() 
700 stub SteamController_Init() 
701 stub SteamController_SetOverrideMode() 
702 stub SteamController_Shutdown() 
703 stub SteamController_TriggerHapticPulse() 
704 cdecl SteamFriends() SteamFriends_
705 stub SteamGameServer() 
706 stub SteamGameServerApps() 
707 stub SteamGameServerHTTP() 
708 stub SteamGameServerInventory() 
709 stub SteamGameServerNetworking() 
710 stub SteamGameServerStats() 
711 stub SteamGameServerUGC() 
712 stub SteamGameServerUtils() 
713 stub SteamGameServer_BSecure() 
714 stub SteamGameServer_GetHSteamPipe() 
715 stub SteamGameServer_GetHSteamUser() 
716 stub SteamGameServer_GetIPCCallCount() 
717 stub SteamGameServer_GetSteamID() 
718 stub SteamGameServer_Init() 
719 stub SteamGameServer_InitSafe() 
720 stub SteamGameServer_RunCallbacks() 
721 stub SteamGameServer_Shutdown() 
722 cdecl SteamHTMLSurface() SteamHTMLSurface_
723 cdecl SteamHTTP() SteamHTTP_
724 cdecl SteamInventory() SteamInventory_
725 cdecl SteamMatchmaking() SteamMatchmaking_
726 cdecl SteamMatchmakingServers() SteamMatchmakingServers_
727 cdecl SteamMusic() SteamMusic_
728 cdecl SteamMusicRemote() SteamMusicRemote_
729 cdecl SteamNetworking() SteamNetworking_
730 cdecl SteamRemoteStorage() SteamRemoteStorage_
731 cdecl SteamScreenshots() SteamScreenshots_
732 cdecl SteamUGC() SteamUGC_
733 cdecl SteamUnifiedMessages() SteamUnifiedMessages_
734 cdecl SteamUser() SteamUser_
735 cdecl SteamUserStats() SteamUserStats_
736 cdecl SteamUtils() SteamUtils_
737 cdecl SteamVideo() SteamVideo_
738 cdecl Steam_GetHSteamUserCurrent() Steam_GetHSteamUserCurrent_
739 cdecl Steam_RegisterInterfaceFuncs( ptr ) Steam_RegisterInterfaceFuncs_
740 cdecl Steam_RunCallbacks( long long ) Steam_RunCallbacks_
741 stub VR_GetControlPanel() 
742 stub VR_GetGenericInterface() 
743 stub VR_GetStringForHmdError() 
744 stub VR_Init() 
745 stub VR_IsHmdPresent() 
746 stub VR_Shutdown() 
747 stub g_pSteamClientGameServer() 
